.gitignore, app/lib/validation.js, app/web/modules/stripe/address.model.js, app/web/modules/stripe/bankAccount.model.js, app/web/modules/stripe/dob.model.js, app/web/modules/stripe/legalEntity.model.js, app/web/modules/stripe/stripe.model.js, app/web/modules/stripe/stripe.model.spec.js, package-lock.json, package.json
This probably slightly overdone PR aims to allow users of toolbox to
fill in partial information about a stripe account and create the account
with stripe with the provided data, whilst ensuring that the minimum
information and defaults are provided.
=> Allow empty fields in stripe account creation

app/web/modules/stripe/legalEntity.model.js, app/web/modules/stripe/stripe.model.spec.js
Fix dob and address model creation in legal entity model
=> Fix stripe form validation

app/web/modules/services/detail.njk
=> Bau fix typo and case

app/web/modules/gateway_accounts/createSuccess.njk
See commit message
Code review
=> BAU: Fix typo

app/web/modules/gateway_accounts/confirm.njk, app/web/modules/gateway_accounts/create.njk, app/web/modules/gateway_accounts/createSuccess.njk, app/web/modules/gateway_accounts/detail.njk, app/web/modules/gateway_accounts/overview.njk, app/web/modules/landing/landing.njk, app/web/modules/layout/layout.njk, app/web/modules/services/detail.njk, app/web/modules/services/overview.njk, app/web/modules/services/search.njk, app/web/modules/statistics/by_service.njk, app/web/modules/statistics/filter_comparison.njk, app/web/modules/statistics/filter_date.njk, app/web/modules/stripe/create.njk, app/web/modules/transactions/search.njk
Also replaced some primes (') with proper quotes (‘’)
Also nice way to snoop my way through the files 👀
=> BAU - pedantry part II - use sentence case everywhere

app/lib/pay-request/api_utils/connector.js, app/web/modules/discrepancies/discrepancies.http.js, app/web/modules/discrepancies/index.js, app/web/modules/discrepancies/report.njk, app/web/modules/discrepancies/resolution.njk, app/web/modules/discrepancies/search_results.njk, app/web/router.js
Adds ability to report on and resolve discrepancies between
payment gateway and Pay.
=> PP-4858 Front end for discrepancy reporting and resolution

.gitignore, app/tests/cypress/integration/landing.spec.js, app/tests/cypress/plugins/index.js, app/tests/cypress/support/index.js, app/web/modules/gateway_accounts/gateway_accounts.spec.js, app/web/modules/stripe/stripe.model.spec.js, cypress.json, package-lock.json, package.json
Test runner infrastructure for unit and end to end tests.
=> PP 4894: Toolbox test runners

app/tests/cypress/integration/landing.spec.js, app/web/modules/gateway_accounts/gateway_accounts.spec.js, app/web/modules/statistics/statistics.http.js, app/web/modules/stripe/clientjs/parse-csv.js, app/web/modules/stripe/stripe.model.spec.js
For upcoming CI integration - ensure current code passes linting
standards.
=> BAU: Fix minor lint issues to pass standard lint

Jenkinsfile
Initial repository Jenkinsfile pipeline
=> PP-4895 Jenkins infrastructure

app/web/modules/discrepancies/report.njk, app/web/modules/layout/layout.njk
So people can find this amazing feature, and use it correctly \o/
=> PP-4858 Add link in side nav and hint for discrepancy search

package.json, scripts/run-dev
Reflect changes in templates on changes for dev server watch script.
=> PP-5027: Copy templates on dev watch process

.eslintrc.json, .vscode/settings.json, package-lock.json, package.json, src/assets/payuk-toolbox.scss, src/lib/errors/index.js, src/lib/pay-request/api_utils/adminUsers.js, src/lib/pay-request/api_utils/adminUsersTypes.ts, src/web/modules/common/errorSummary.njk, src/web/modules/common/validationErrorFormat.ts, src/web/modules/layout/flash.njk, src/web/modules/layout/layout.njk, src/web/modules/services/detail.njk, src/web/modules/stripe/basic.http.ts, src/web/modules/stripe/basic.njk, src/web/modules/stripe/index.js, src/web/router.js, tsconfig.json
- Add page for creating a Stripe account using the service details stored in Adminusers rather than requiring the user to enter them
- This creates an account without Responsible person, VAT number, Bank Account details as the end user will be required to fill these out later
- All of this is in Typescript 🔥 
- Also, add handling of flash in layout.njk by showing a flash container above the main body of the page
=> PP-5027 Add Stripe account creation from stored data

src/lib/errors.ts, src/lib/pay-request/api_utils/adminUsers.js, src/web/errorHandler.ts, src/web/server.js
- Make lib/errors typed
- Rename web/errors to errorHander and type-ify
Co-authored-by: Steven Fountain <steven.fountain@digital.cabinet-office.gov.uk>
=> PP-5027 Make error handling typed

package-lock.json, package.json, src/lib/logger.ts, tsconfig.json
* Add @types/cls-hooked
* Update logger file to use Typescript
=> PP-5027: Logger Typescript definition

src/web/modules/stripe/basic/basic.http.ts
Quick fix for template renderer path, this will allow the feature branch to be used before we get it merged.
=> BAU: Quick fix for Stripe basic accounts

package-lock.json, package.json, src/web/server.js
* helmet library for sensible HTTP header defaults
* include configuration for blocking all CSP requests - https://helmetjs.github.io/docs/csp/
=> PP-5324 Sensible production HTTP header defaults

src/web/errorHandler.ts, src/web/server.js
Handle requests that don't match any routes -- don't respond specifically for any request that has not been authenticated.
=> PP-5324 404 handler: ignore unauthenticated requests

scripts/generate-dev-environment, src/config/server.js, src/web/server.js
* server configuration for cookie secret
* remove hardcoded value 
* add test cookie to generate local dev environment script
=> PP-5324 Extract hardcoded cookie session

package-lock.json, package.json, src/lib/pay-request/client.js, src/web/errorHandler.ts, src/web/modules/discrepancies/discrepancies.http.js, src/web/modules/discrepancies/report.njk, src/web/modules/discrepancies/search_results.njk, src/web/modules/gateway_accounts/confirm.njk, src/web/modules/gateway_accounts/create.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/services/branding.njk, src/web/modules/services/link_accounts.njk, src/web/modules/services/search.njk, src/web/modules/services/services.http.ts, src/web/modules/statistics/filter_comparison.njk, src/web/modules/statistics/filter_date.njk, src/web/modules/statistics/statistics.http.js, src/web/modules/stripe/basic/basic.http.ts, src/web/modules/stripe/basic/basic.njk, src/web/modules/stripe/create.njk, src/web/modules/stripe/stripe.http.js, src/web/modules/transactions/search.njk, src/web/modules/transactions/transactions.http.js, src/web/server.js
* add csurf library for token generation 
* generate token for `POST/PUT` requests that could mutate state
=> PP-5324 Generate CSRF token for mutable requests

Jenkinsfile
`post` steps for Jenkinsfile build
=> BAU Push Jenkinsfile build step metrics

src/web/modules/transactions/transactionSearch.model.js, src/web/server.js
* Strip and ignore fields not related to search attribute model
=> BAU: ignore non-model related attributes on search

src/lib/pay-request/api_utils/adminUsers.js, src/web/errorHandler.ts, src/web/modules/services/detail.njk, src/web/modules/users/users.http.ts, src/web/modules/users/users.show.njk, src/web/modules/users/users.update_email.njk, src/web/modules/users/users.update_phone.njk, src/web/router.js
User management web module
* View user details 
* Update phone number/ email 
* Disable/ enable 
* Remove from service subscriptions 
Required: 
Supersedes https://github.com/alphagov/pay-toolbox/pull/108
=> PP-5030 User details admin feature

.eslintrc.json, README.md, scripts/local-tunnel.sh, src/lib/auth.js, src/lib/auth.spec.js, src/lib/auth/github/githubStrategy.spec.js, src/lib/auth/passport.js, src/lib/pay-request/api_utils/adminUsers.js
* test Codacy integration
* address README.md lint issues
* address shell script lint issues
=> BAU Shell scripts, README lint issues

src/lib/pay-request/client.js
* service user requests are being blocked on load time + max size, adjust these values 
* specify `keepAlive` in case that's confusing the TCP connection
=> BAU Update REST client defaults blocking services loading

src/web/modules/payouts/reconcile.ts
* Filter matching refunds for refunds that have succeeded
=> BAU Handle error status for refund matching

src/lib/pay-request/api_utils/connector.js
* Fix api route for get charge by gateway transaction
=> BAU Point Connector to the right API route

src/web/modules/payouts/csv.ts, src/web/modules/payouts/payTransaction.ts, src/web/modules/payouts/payouts.http.ts, src/web/modules/payouts/payouts_show.njk, src/web/modules/payouts/reconcile.ts, src/web/router.js
* route to list current payout page as CSV (download attachment) 
* fix: account for legacy charge amounts (without fee or net amount)
=> BAU Export payout page as CSV

scripts/generate-dev-environment, src/config/services.js, src/lib/pay-request/client.js, src/lib/services.store.js
* ledger default URL added to generate dev environment
* ledger `pay-request` client default configuration
=> PP-5398 Add ledger service configuration

src/lib/pay-request/api_utils/index.js, src/lib/pay-request/api_utils/ledger.js, src/lib/pay-request/client.js, src/web/modules/transactions/transactions.http.ts, src/web/router.js
* add pay-request /transaction helper for pay-request
* placeholder transaction show handler
=> PP-5398 pay-request utilities for ledger

src/assets/payuk-toolbox.scss, src/web/modules/layout/layout.njk, src/web/modules/transactions/payment.njk, src/web/modules/transactions/transactions.http.ts
* get gateway account and service to compliment transaction data
* show transaction template for payments
=> PP-5398 Show transaction template and handler

src/assets/payuk-toolbox.scss, src/lib/pay-request/api_utils/ledger.js, src/tests/fixtures/payment.ts, src/web/modules/layout/layout.njk, src/web/modules/transactions/@types/transactions.d.ts, src/web/modules/transactions/payment.njk, src/web/modules/transactions/search.njk, src/web/modules/transactions/status.macro.njk, src/web/modules/transactions/transactions.http.ts, src/web/router.js
* basic transactions search - redirect to transactions view (lookup by reference etc. to be added)
* search template 
* platform admin override query
* routes added for search
=> PP-5389 Ledger transactions search (basic)

src/assets/payuk-toolbox.scss, src/lib/pay-request/api_utils/ledger.js, src/web/modules/transactions/payment.njk, src/web/modules/transactions/transactions.http.ts
* events view for payments (very basic version) 
* cleanup based on previous pull request comments
=> PP-5389 Use introduced Ledger events end point

src/web/modules/transactions/transactions.http.ts
* endpoint was updated to send JSON not a String
* don't parse already valid JSON
=> BAU Fix transaction events string parse

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/modules/gateway_accounts/surcharge.njk, src/web/router.js
* update connector request utility to update surcharge values from connector
* link together gateway accounts and update surcharge utils
=> BAU Set gateway account corporate surcharge feature

src/web/modules/transactions/payment.njk
* payment 'show' template doesn't show year of payments
* add a field to show that
=> BAU Add payment detail date field to show year

package-lock.json
* eslint-utils vulnerability patch
=> BAU Address npm audit security vulnerability

src/lib/pay-request/api_utils/ledger.js
* filter ledger transactions by payments
=> BAU Fix invalid refunds showing up in payments

src/lib/pay-request/api_utils/adminUsers.js, src/web/modules/layout/layout.njk, src/web/modules/users/search.njk, src/web/modules/users/users.http.ts, src/web/router.js
* admin users `findUser` utility method
* confusingly search on the `username` field, search on `email` field isn't allowed
* search page template
* hook up router gubbins
* (unrelated) sensible side bar navigation order
Contributes to https://github.com/alphagov/pay-toolbox/issues/58
Closes https://github.com/alphagov/pay-toolbox/issues/58 with https://github.com/alphagov/pay-toolbox/pull/190
=> BAU Lookup user by email from adminusers

src/web/modules/discrepancies/report.njk, src/web/modules/gateway_accounts/overview.njk, src/web/modules/layout/layout.njk, src/web/modules/services/overview.njk, src/web/modules/services/search.njk, src/web/modules/statistics/by_service.njk, src/web/modules/statistics/comparison.njk, src/web/modules/statistics/filter_comparison.njk, src/web/modules/statistics/filter_date.njk, src/web/modules/statistics/overview.njk, src/web/modules/transactions/legacy/search.njk, src/web/modules/transactions/search.njk
* standardise headers with platform supertitles
* standardise IDs in list view
* simplifiy gateway account link logic
=> BAU Standard toolbox page layouts

src/lib/pay-request/api_utils/ledger.js
Reverts alphagov/pay-toolbox#209
=> Revert "BAU - Remove transaction_type query param"

src/web/modules/services/overview.njk
Remove additional column and put organisation name on the line below the service name, if one is set.
=> BAU Put organisation in same column as service name

.hadolint.yaml
=> Add Hadolint configuration from pay-code-analysis-config

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/email_branding.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/router.js
Currently no ability to remove the branding, I'll add that later if I have time
=> Issue #28: Add ability to update email custom branding

package-lock.json, package.json
Reverts alphagov/pay-toolbox#223
=> Revert "Bump govuk-frontend from 2.13.0 to 3.3.0"

src/web/modules/transactions/payment.njk
Payee is the person who receives the money
=> It's payer not payee

.eslintrc.json, package.json, src/lib/errors.ts, src/lib/logger.ts, src/lib/pay-request/types/adminUsers.ts, src/web/modules/common/validationErrorFormat.ts, src/web/modules/gateway_accounts/gateway_accounts.exceptions.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/payouts/csv.ts, src/web/modules/payouts/page.ts, src/web/modules/payouts/reconcile.ts, src/web/modules/services/branding.spec.ts, src/web/modules/services/services.http.ts, src/web/modules/stripe/basic/basic.http.ts, src/web/modules/transactions/@types/transactions.d.ts, src/web/modules/transactions/transactions.http.ts, src/web/modules/users/UpdateEmailForm.ts, src/web/modules/users/UpdatePhoneNumberForm.ts, src/web/modules/users/users.http.ts
Issues stopping files from being linted correctly
* Potential globbing issues with passing in source folder on different machines -- explicitly pass in all `.ts` and `.js` files
* TypeScript lint on JavaScript files -- override `eslintrc` during the JS -> TS transition
=> BAU (v1) Lint all files

package-lock.json
`npm audit` is blocking CI, patch low risk vulnerability
=> BAU Patch vulnerability in `copyfiles` version

README.md
* Add CI badges for style, vulnerabilities and code health 
* README lint issues
=> BAU README CI badges

package-lock.json, package.json, src/lib/pay-request/api_utils/ledger.js, src/lib/pay-request/api_utils/ledger.spec.js, src/web/modules/transactions/list.njk, src/web/modules/transactions/search.njk, src/web/modules/transactions/transactions.http.ts
`Find a transaction` tool supports looking up payment references. 
In priority order:
* look for transaction with an exact ID match 
* look for transactions with exact reference match
* resource not found
Transaction list table supports filtering by reference as payment reference isn't guaranteed to be unique.
=> BAU Find transaction by reference

src/web/modules/transactions/list.njk, src/web/modules/transactions/payment.njk, src/web/modules/transactions/status.macro.njk
* pass refundability status and total amount refunded into payment
status badge
* present 'Refunded' or 'Partial refund' depending on the status of they
payment
=> BAU Payment status badge represents refunded state

src/web/modules/transactions/payment.njk
* use table template to iterate through key value pairs in metadata
* same pattern as "processing details"
Co-authored-by: Maria Jankowiak <maria.jankowiak@digital.cabinet-office.gov.uk>
=> BAU Show metadata if it exists

src/web/modules/gateway_accounts/detail.njk
In order to allow adding the modify of the property at the row level, like:
Before:
After:
=> [PP-5938] Replace table with summary-list for details view

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/router.js
* add action on Gateway Account detail page to link to toggle route
* add helper method for calling connector route
* add GET route for toggling flag (calls helper method)
=> PP-5938 Toggle blocking prepaid cards

package-lock.json, package.json, src/config/common.js, src/config/sentry.js, src/lib/logger.ts, src/lib/requestLoggingMiddleware.ts, src/web/server.js
So that we can search in Splunk in a consistent way, use the same format
for logging with the same keys as we do for other apps.
=> BAU Make logging consistent with other apps

src/lib/pay-request/api_utils/ledger.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/transactions/csv.njk, src/web/modules/transactions/transactions.http.ts, src/web/router.js
* set `Accept` header to `text/csv` to get transaction data by CSV 
* simple web module to request with basic params
=> PP-5970 Simple account CSV transaction export

src/lib/pay-request/api_utils/adminUsers.js
Use the new endpoint in adminusers to reset a user's second factor
method to SMS.
=> PP-5313 Enable reset second factor

manifest.yml
Adds a manifest.yml file allowing toolbox to run on PAAS using the node js buildpack.
=> Add cf manifest.yml file

package-lock.json, package.json
Branching from master isn't passing CI's `npm audit` - patch the vulnerability.
=> BAU npm audit patch vulnerabilities

src/web/modules/transactions/csv.njk, src/web/modules/transactions/transactions.http.ts, src/web/router.js
Prototype for passing the core http library stream through to express for transaction CSV downloads.
=> PP-6053 TCP stream CSV downloads

src/web/modules/transactions/transactions.http.ts
* high level libraries have been doing this for us
* http library needs specific port/ host set
=> BAU Parse environment configuration for transaction stream

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/router.js
The button will be shown if MOTO payments are disabled for the gateway account.
=> PP-6073: Enable MOTO payment button

browser/src/dashboard/Dashboard.tsx
* aggregate timeseries point can be accessed before that data is
available from the database
* ensure that default values are used if this point hasn't yet been
fetched
=> BAU Fix default point access on dashboard aggregate sync

src/web/modules/gateway_accounts/api_keys.njk
the field label "Issued date" was actually showing "last used date"
=> BAU: bugfix display of api tokens

src/assets/payuk-toolbox.scss, src/web/modules/gateway_accounts/api_keys.njk, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/email_branding.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/surcharge.njk, src/web/modules/landing/landing.njk, src/web/modules/layout/layout.njk, src/web/modules/transactions/list.njk, src/web/modules/transactions/payment.njk, src/web/modules/transactions/refund.njk, src/web/modules/transactions/transactions.http.ts
Banner to clearly differentiate entities in Toolbox that are made against test or live accounts.
* quickly checking if abnormal behaviour is just down to testing or if it should be investigated.
* make changes to test entities more confidently knowing that it won't impact a live service
**Desktop** 
**Mobile**
=> BAU Clearly differentiate test data (banner) 

src/lib/gatewayAccounts.ts, src/lib/pay-request/types/adminUsers.ts, src/lib/pay-request/types/connector.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/payment_links/payment_links.http.ts
Add fields to Service and GatewayAccount type interfaces to allow this
=> Move aggregating services by account id to shared function

src/config/aws.js, src/config/index.js, src/web/modules/transactions/update/update.http.ts
Once the transactions update CSV has been validated, upload it to S3
=> PP-6219 Upload file to S3

src/web/modules/transactions/update/upload.njk
Add copy to the update transactions page detailing the format required for the CSV file.
=> PP-6219 Add instructions for CSV format

src/web/modules/transactions/update/success.njk, src/web/modules/transactions/update/update.http.ts, src/web/router.js
Add and redirect to success page after starting a successful payment
update job.
* Provide reference for job id using gov uk panel
* Link to example Splunk search containing job reference
**Success status page**
=> PP-6219 Update transactions explicit success redirect

src/web/modules/layout/layout.njk, src/web/modules/transactions/update/upload.njk
* link to `/transactions/update` in main nav
* update copy to make header schema clearer
=> PP-6219 Link to transaction update in main nav

src/web/modules/layout/layout.njk
=> BAU Fix closing tag for main nav

src/web/modules/transactions/update/update.http.ts, src/web/modules/transactions/update/upload.njk
Ledger expects a very specific formats for dates. Allow the user to give the date in any ISO_8601 format and transform this into the format expected by ledger
=> PP-6219 Format user provided date for ledger

src/web/modules/transactions/update/upload.njk
Description of how event naming links with Ledger.
=> PP-6382 Info on naming and salient events (STROOP-30)

src/web/modules/transactions/update/update.http.ts
Ensure default payment update events identify who the responsible
administrative user was that requested the change. If nothing is
provided use the GitHub session user.
=> PP-6382 Add GitHub username/ display name to payment update events (STROOP-30)

src/lib/format.js, src/lib/pay-request/api_utils/ledger.js, src/web/modules/layout/layout.njk, src/web/modules/ledger_payouts/list.njk, src/web/modules/ledger_payouts/payout.http.ts, src/web/modules/transactions/list.njk, src/web/modules/transactions/transactions.http.ts, src/web/router.js, src/web/server.js
- Added payout section to list payouts processed to Ledger.
Gives us the ability to view payouts in Ledger, filter by status and view related transactions.
------
-----
=> BAU - Add Payouts (from Ledger) page

src/web/modules/gateway_accounts/detail.njk
Description:
- Displays the 3DS version for the particular gateway account
=> PP-6364 - Displays 3DS version in Toolbox

env-map.yml, manifest.yml, scripts/generate-dev-environment, src/assets/payuk-toolbox.scss, src/config/services.js, src/web/modules/gateway_accounts/createSuccess.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
- On the Stipe live gateway created success page - we now display the following:
- Go Live URL
- Statement Descriptor
- Payout Statement Descriptor
- Only displayed for Stripe services
=> PP-6661 Show Stripe go live onboarding details

src/lib/pay-request/api_utils/adminUsers.js, src/lib/pay-request/types/connector.ts, src/web/modules/gateway_accounts/confirm.njk, src/web/modules/gateway_accounts/create.njk, src/web/modules/gateway_accounts/gatewayAccount.model.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/gateway_accounts.spec.js, src/web/modules/services/detail.njk
- Service detail page > display:
- Sector
- Is internal service flag
- `WHEN_LIVE_DATE`
- When adding new Gateway account > Allow adding new options for
- Sector
- Is internal service flag
- Automatically set `WHEN_LIVE_DATE`
=> Pp 6257 collect new service information when gateway account created

src/web/modules/transactions/update/upload.njk
Update instructions on update transactions page to describe some pitfalls and point to examples.
=> BAU — Update instructions on update transactions page

package-lock.json, package.json
- Bump the version of pay-java-commons
=> BAU Bump Toolbox Pay-Java-Commons

package.json
- Downgrade the version of the node engine for buildpack compatibility
=> PP-6659 Downgrade Node Engine Version

src/web/modules/transactions/update/update.http.ts
- If event_type === PAYMENT_STATUS_CORRECTED_TO_SUCCESS_BY_ADMIN or REFUND_STATUS_CORRECTED_TO_SUCCESS_BY_ADMIN
- Validate these fields - refund_status, refund_amount_refunded refund_amount_available
- For event_type === PAYMENT_STATUS_CORRECTED_TO_SUCCESS_BY_ADMIN
- Also validate captured_date.
=> PP-6497 Update CSV validation

src/web/modules/transactions/update/update.http.ts
- Remove the transformation of `refund_amount_available` & `refund_amount_refunded` to a number in the CSV.
- As it is not required
- Add unnecessary complexity
=> BAU - Refactor CSV Validation

src/web/modules/transactions/refund.njk
- Removes reference on refund page as it has been moved to gateway_transaction_id (added to the page)
=> PP-6766 Remove reference on refund page

src/lib/pay-request/api_utils/ledger.js, src/web/modules/transactions/list.njk
- Enables  `limit_total` to list transactions from ledger and sets `limit_total_size`
=> PP-6768 Enable `limit_total` for ledger transactions

src/web/modules/layout/layout.njk
- Add a dashboard link
- Display git prowess through ```git commit -n```
=> BAU Add Dashboard Link

LICENCE, README.md
Following the [GDS Way guidelines for Licence files](https://gds-way.cloudapps.digital/manuals/licensing.html#licensing).
=> PP-7250 Add Licence file

package-lock.json, package.json
Snyk check was failing https://snyk.io/vuln/SNYK-JS-LODASH-590103
=> Bump lodash to resolve vulnerability

.secrets.baseline, src/lib/gatewayAccounts.ts, src/lib/pay-request/api_utils/adminUsers.js, src/web/modules/gateway_accounts/csv_data.ts, src/web/modules/gateway_accounts/csv_with_admin_emails.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/modules/gateway_accounts/overview.njk, src/web/router.js
=> PP-7663: Download csv with Admin user emails

package-lock.json, package.json
This pull request has 4 commits.
1. The first commit upgrades [@types/lodash](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/lodash) from 4.14.136 to 4.14.168.
- [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
- [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/lodash)
2. The second commit upgrades [@types/express](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/express) from 4.17.0 to 4.17.11.
- [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
- [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/express)
3. The third commit upgrades [typescript](https://github.com/Microsoft/TypeScript) from 3.8.3 to 4.1.3.
- [Release …
=> BAU: Update dev dependencies

src/web/modules/gateway_accounts/csv_data.ts
Commit that doesn't do anything. We just want a new image to test the toolbox
deploy-to-fargate concourse pipeline.
=> PP-7800: Need a new toolbox image

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/search.njk
Might be useful if people send us the URL containing the external ID, or
just for debugging.
=> BAU Allow find gateway account by external id

package-lock.json, package.json
Reverts alphagov/pay-toolbox#1036
This causes the payments dashboard to be quietly unhappy. The build is fine but I think the slight events API change throws an error on page load.
=> Revert "Bump react-spring from 9.0.0 to 9.1.0"

.vscode/launch.json, README.md
Add launch.json with config to run the app in debug mode, and add instructions to README.
=> PP-7965 Add VS Code debug config

src/web/modules/statistics/performance.http.ts, src/web/modules/statistics/performancePage.njk, src/web/router.js
Demonstrate how we can update the performance page more sustainably, in futute swapping out the manual process for an automated process that generates a JSON file that is used to build the static page.
=> PP-7931 Generate JSON data for performance page

src/web/modules/platform/dashboard.http.ts
- Use YYYY for year instead of YYY (which returns 212021-04-28)
=> BAU - Fix year format

src/lib/pay-request/api_utils/connector.js, src/web/modules/events/emitByDate.njk, src/web/modules/events/emitById.njk, src/web/modules/events/events.http.js, src/web/modules/events/failure.njk, src/web/modules/events/index.js, src/web/modules/events/parityChecker.njk, src/web/modules/events/success.njk, src/web/modules/layout/layout.njk, src/web/router.js
- Add the administrative tasks to toolbox, with a user interface and
connector client changes for each of the tasks
=> PP-7978 Add Administrative Tasks To Toolbox

src/lib/pay-request/api_utils/connector.js, src/web/modules/events/parityChecker.njk
- Export the new connector methods in `connector.js
=> PP-8118 Add Connector Exports

.github/workflows/run-tests.yml, src/tests/.env
- Added workflow to run unit tests on Github actions
=> PP-8083 Add action to run tests

src/web/modules/events/emitByDate.njk
- Add date format help behind a details component
=> PP-7977 Add Date Format Help

src/web/modules/events/emitByDate.njk
- Stipulate that we expect DateTime's in UTC
=> PP-8118 Stipulate UTC Zone

src/web/modules/events/parityChecker.njk
- Be clearer regarding what each field is used for
=> PP-8118 Update Parity Checker Text

src/lib/pay-request/api_utils/connector.js, src/web/modules/events/emitById.njk, src/web/modules/events/events.http.js, src/web/modules/events/parityChecker.njk
- Fix a number of misconfigurations in the API spec between toolbox and connector for the task
=> PP-8118 Fix Toolbox Connector Task API Spec

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
Instruct that 3D secure must be enabled.
=> BAU Add instructions for sending payer IP to gateway

src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts
- Restrict switching provider to accounts with ACTIVE credential. This ensures that there is an active credential to switch from and creates a new credential to switch to.
=> PP-8282 Allow switching provider only if current provider is fully configured

src/lib/gatewayAccounts.ts, src/web/modules/gateway_accounts/filter.njk, src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts
- Added filter to search for gateway accounts switching PSP
- Also added logging when provider switch is enabled on gateway account
=> PP-8298 Filter gateway accounts switching PSP

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/router.js
- Added functionality to enable/disable `send_reference_to_gateway` field on gateway account.
=> PP-8450 Add toggle for `send_reference_to_gateway`

package-lock.json
- update known vulnerabilities:
upgrade glob-parent to version 5.1.2 or higher
upgrade color-string to version 1.5.5 or higher
=> PP-8427 address vulnerabilities

src/lib/pay-request/api_utils/products.js, src/lib/pay-request/api_utils/redact.js, src/lib/pay-request/types/products.ts, src/web/modules/payment_links/detail.njk, src/web/modules/payment_links/overview.njk, src/web/modules/payment_links/payment_links.http.ts, src/web/router.js
Add a details page for payment links with a button to toggle whether CAPTCHA is enabled for the payment link.
Link to the details page from the list payment links view.
=> PP-8551 Allow updating require CAPTCHA

package-lock.json, package.json
- Bumps stripe-latest module to latest version 
- Change log https://github.com/stripe/stripe-node/compare/v8.167.0...v8.174.0
=> PP-8555 Bump stripe-latest version from 8.167.0 to 8.174.0

.editorconfig
- Added standard editorconfig from https://gds-way.cloudapps.digital/manuals/programming-languages.html
=> BAU - Add standard .editorconfig

src/config/aws.js, src/web/modules/transactions/update/update.http.ts
Update transaction updater to use the new fargate version of the task.
=> PP-8532: Use fargate update transactions task

src/web/modules/transactions/update/update.http.ts
- Sets requires_3ds as a boolean field when upload csv to S3
=> PP-8627 Pass requires_3ds as boolean to s3 stream

package-lock.json, package.json
Reverts alphagov/pay-toolbox#1236
Reference https://github.com/alphagov/pay-toolbox/pull/1218
=> Revert "Bump @sentry/node from 6.12.0 to 6.14.0"

src/lib/pay-request/types/connector.ts, src/web/modules/gateway_accounts/csv_data.ts, src/web/modules/gateway_accounts/surcharge.njk
Description:
- Removes functionality to update prepaid corporate credit cards
=> PP-8785 - Remove prepaid corporate credit card

README.md, src/lib/pay-request/types/adminUsers.ts, src/web/modules/services/detail.njk, src/web/modules/services/services.http.ts
=> PP-9060: Add link to email all admin users in one shot

src/lib/gatewayAccounts.ts, src/web/modules/gateway_accounts/filter.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/search.njk
Depends on https://github.com/alphagov/pay-connector/pull/3419
Add search by Stripe Account ID or Merchant ID on 'find a gateway account' page.
If 1 result is found, redirect to that gateway account detail page, else redirect to a search page showing all matching results
-------
=> PP-9013: search by stripe account ID or merchant ID

src/web/modules/stripe/basic/account.ts
- Checks if address and telephone number are available (as these are not collected as part of switching PSP) before creating a stripe account - for services switching PSP.
=> PP-8836 Switch PSP - check for org address and telephone number

.github/workflows/run-tests.yml, Dockerfile, package-lock.json, package.json
Bump:
* node to 12.22.10
* alpine to 3.15
=> PP-9223: Update to node 12.22.10 and alpine 3.15

src/web/modules/layout/user_banner.njk, src/web/modules/services/services.http.ts, src/web/server.js
Fixes a bug where GitHub avatars were being blocked by CSP
=> PP-9442 Fix GitHub avatars not loading

src/web/modules/gateway_accounts/agent_initiated_moto.njk, src/web/modules/gateway_accounts/csv.ts, src/web/modules/gateway_accounts/csv_with_admin_emails.ts
=> BAU — s/initated/initiated

src/lib/pay-request/api_utils/adminUsers.js, src/web/modules/services/search.njk, src/web/modules/services/search_results.njk, src/web/modules/services/services.http.ts
- added ability to search services by name and merchant
- added new view to list search results
- updated `api_utils` with new adminusers search endpoint
=> PP-9443 Add additional search options to `find a service`

src/lib/format.js
- Make the date format match the GOV.UK style (e.g. 6 May 2022)
=> PP-9547 change date formatting

src/web/modules/payment_links/csv.ts
- Added reference hint field to the payment links CSV download
=> PP-9453 Add reference hint to payment links CSV download

package-lock.json, package.json, src/lib/auth.js
Reverts alphagov/pay-toolbox#1378
=> Revert "Bump passport from 0.5.3 to 0.6.0"

src/web/modules/transactions/list.njk
- Added conditional statements to list all data for a single payout and ensure pagination stays with the payout
=> PP-9496 fixing pagination of transactions for payouts

src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts, src/web/modules/stripe/basic/test-account.http.ts
- Added organisations detail field
=> PP-9207 Mark organisation details complete when Stripe test account is created

src/web/modules/transactions/update/upload.njk
- add a small reminder that `reason` has been renamed to `updated_reason`
=> PP-9925 add a small reminder that `reason` has been renamed

src/web/modules/transactions/update/update.http.ts, src/web/modules/transactions/update/upload.njk
- add a bit more explanation of what it used for to `reason`.
=> PP-9925 add a bit more text to reason

src/lib/pay-request/api_utils/products.js, src/web/modules/payment_links/detail.njk, src/web/modules/payment_links/payment_links.http.ts, src/web/router.js
- new journey has been enabled for all payment links, we no longer need the ability to enable it one by one
=> PP-9952 remove new payment links journey

browser/src/dashboard/Dashboard.tsx
Following feedback and questions from people observing the dashboard, add a simple title and description that explains what the money represents and makes it clearer what is shown.
=> BAU Live payments dashboard title

src/web/modules/layout/layout.njk, src/web/modules/payment_links/payment_links.http.ts, src/web/modules/payment_links/search.njk, src/web/router.js
Add page that allows searching for a payment link by external ID
=> BAU Add Find payment link page

src/lib/gatewayAccounts.ts, src/lib/pay-request/typed_clients/services/admin_users/client.ts, src/lib/pay-request/typed_clients/services/connector/client.ts, src/lib/pay-request/typed_clients/services/connector/types.ts, src/lib/pay-request/typed_clients/shared.ts, src/web/modules/gateway_accounts/csv_data.ts
Use typed clients for csv_data.ts
=> PP-9814 Use typed clients for gateway account CSV download

src/lib/pay-request/typed_clients/client.ts, src/lib/pay-request/typed_clients/services/admin_users/types.ts, src/lib/pay-request/typed_clients/services/connector/client.ts, src/lib/pay-request/typed_clients/services/connector/types.ts, src/lib/pay-request/typed_clients/services/products/client.ts, src/lib/pay-request/typed_clients/services/products/types.ts, src/lib/pay-request/typed_clients/services/public_auth/client.ts, src/lib/pay-request/typed_clients/services/public_auth/types.ts, src/lib/pay-request/typed_clients/utils/error.ts, src/web/modules/gateway_accounts/gatewayAccount.model.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts
Switch to using the new typed clients in the gateway accounts controller. Add in missing methods to the clients as required.
=> PP-9814 Use typed clients for gateway accounts controller

src/lib/pay-request/typed_clients/services/ledger/client.ts, src/lib/pay-request/typed_clients/services/ledger/types.ts, src/web/modules/ledger_payouts/list.njk, src/web/modules/ledger_payouts/payout.http.ts
Used typed clients for payout.http.ts
=> PP-9814 Use typed clients for list payouts

src/lib/pay-request/typed_clients/services/products/client.ts, src/lib/pay-request/typed_clients/services/products/types.ts, src/lib/pay-request/typed_clients/utils/redact.ts, src/web/modules/payment_links/payment_links.http.ts
Update payment_links.http.ts to use typed clients.
=> PP-9814 Use typed clients for payment links

src/lib/pay-request/typed_clients/services/ledger/client.ts, src/web/modules/platform/dashboard.http.ts
Use typed clients for dashboard.http.ts
=> PP-9814 Use typed clients for dashboard

src/lib/pay-request/typed_clients/services/admin_users/client.ts, src/lib/pay-request/typed_clients/services/admin_users/types.ts, src/lib/pay-request/typed_clients/services/connector/client.ts, src/lib/pay-request/typed_clients/services/connector/types.ts, src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts, src/web/modules/stripe/basic/account.ts, src/web/modules/stripe/basic/basic.http.ts, src/web/modules/stripe/basic/test-account.http.ts, src/web/modules/stripe/model/account.model.ts, src/web/modules/stripe/model/person.model.ts
Use typed clients for controllers involved in creating Stripe accounts and for PSP switching.
=> PP-9814 Use typed clients for Stripe account creation

src/web/modules/users/users.show.njk
If no telephone number is set for the user, display the text "(None set)" in the "Phone" row on the user details page.
=> PP-10048 Handle user phone number not set

src/lib/pay-request/services/ledger/client.ts, src/lib/pay-request/services/ledger/types.ts, src/lib/pay-request/shared.ts, src/web/modules/agreements/states.ts
- Setting the components for the agreement list page.
- Page will not be accessibile at the moment.
=> PP-10409 Agreements list page - setting up the page.

src/lib/pay-request/services/ledger/client.ts, src/lib/pay-request/services/ledger/types.ts, src/web/modules/agreements/agreements.http.ts, src/web/modules/agreements/list.njk, src/web/modules/agreements/states.ts, src/web/modules/agreements/status.macro.njk, src/web/modules/gateway_accounts/detail.njk, src/web/modules/layout/layout.njk, src/web/router.js
- Create new Agreement list page.
- Similar to the transaction list page but for agreements.
=> PP-10409 Setup Agreement list page

src/web/modules/gateway_accounts/detail.njk
Gateway detail page
- In the `Toolbox configuration settings` section, show the recurring flag.
=> PP-10634 Gateway detail page - show recurring flag

src/web/modules/agreements/status.macro.njk
- Change display text from `needs more information` to `created`. As that is more helpful for support people and fits better in the table.
=> PP-10634 List agreements - update created tag

src/assets/payuk-toolbox.scss, src/web/modules/ledger_payouts/list.njk, src/web/modules/transactions/status.macro.njk
- Update the tag colours to use the CSS classes from the design system.
- Remove the old classes
=> PP-10634 Update status tags

src/web/modules/agreements/agreements.http.ts, src/web/modules/agreements/search.njk, src/web/router.js
- Add new route and search page for agreements.
- Only displaying the page for now.
- Will manage the post action in a future PR
- Will add to the left hand menu once the POST controller is done.
=> PP-10636 Add agreements search page

src/web/modules/agreements/agreements.http.ts, src/web/modules/layout/layout.njk, src/web/router.js
- Enable `find by agreeement` in the left hand menu
- Add the code to perform the search so that it behaves similar to `find by transaction`
=> PP-10636 Find agreement - add search functionality

src/web/modules/agreements/detail.njk, src/web/modules/transactions/list.njk, src/web/modules/transactions/transactions.http.ts
- Agreements detail page - add button to show all transactions for an agreement.
- Transaction list page - add filter to show transactions for an agreement. This will be linked from the new button on the agroeement detail page.
=> PP-10490 Agreements detail page and transaction list page updates

.github/workflows/run-tests.yml
Located and replaced all usages of set-output commands in run-tests.yml workflows.
=> PP-10675:replaced all usages of set-output in run-tests.yml

src/lib/pay-request/client.ts, src/lib/pay-request/services/webhooks/client.ts, src/lib/pay-request/services/webhooks/types.ts, src/lib/pay-request/shared.ts, src/web/modules/webhooks/overview.njk, src/web/modules/webhooks/webhooks.http.ts, src/web/router.js
- Initial commit for setting up the Webhooks list page.
- Create new client and types.
- Display a basic page for now - to check that the Webhooks client is working.
- Will update this page in a future PR.
=> PP-10734 Webhook - list page

src/lib/pay-request/client.ts
Fix reference for the client setup for Webhooks
=> PP-10734 Fix bug in the pay-request client with Webhooks

src/lib/pay-request/services/connector/types.ts, src/lib/pay-request/services/webhooks/types.ts, src/web/modules/webhooks/webhooks.http.ts, src/web/router.js
- Update the call to the Webhooks service to pass the 'live' parameter
- Once this has been checked on test env, will add a toggle between 'live' & 'test'
- Will also update the Nunjucks with the right styling
=> PP-10734 Webhooks list page - fix call to service

src/web/modules/gateway_accounts/detail.njk, src/web/modules/webhooks/overview.njk, src/web/modules/webhooks/status.macro.njk, src/web/modules/webhooks/webhooks.http.ts
- Add button to the gateway account detail page - to view webhooks
- Add the styling to the webhook overview page
=> PP-10734 Webhooks list page - update styling and add button

src/web/modules/webhooks/overview.njk, src/web/modules/webhooks/status.macro.njk
- Rename macro to `webhookStatusTag`
=> PP-10734 Webhook list - update status macro

scripts/generate-dev-environment.js
The new webhooks service will be spun up locally using docker compose. Add this entry into the script that generates local environment files for development.
=> BAU Include webhooks in local env script

src/lib/pay-request/services/webhooks/client.ts, src/web/modules/webhooks/webhooks.http.ts
- Fix call to the webhooks backend
- Display an empty and complete webhooks page correctly.
=> PP-10734 Webhooks list page - update to display webhooks correctly

src/lib/gatewayAccounts.ts, src/lib/pay-request/services/connector/types.ts, src/web/modules/gateway_accounts/filter.njk
- Allow filtering by recurring flag
=> PP-10491 Gateway list page - add recurring filter

src/lib/pay-request/services/connector/types.ts, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/router.js
- Removed toggle `requires_additional_kyc_data` flag as the functionality is not required anymore.
=> PP-9033 Remove toggle requires_additional_kyc_data

src/lib/pay-request/services/admin_users/types.ts
=> PP-10261 Remove BYOC go live stages

src/web/modules/gateway_accounts/gateway_accounts.http.ts
- Removed references to `additional_kyc_data` task as the task no longer exists in connector
=> PP-9033 Remove references to `additional_kyc_data` task

src/web/modules/layout/layout.njk, src/web/modules/webhooks/search.njk, src/web/modules/webhooks/webhooks.http.ts, src/web/router.js
Add page to find a webhook by external ID and redirect to the webhook details page.
Add link to side navigation.
=> PP-10758 Add find webhook page

src/web/modules/agreements/status.macro.njk
=> PP-10977 fix missing comma

src/web/modules/agreements/status.macro.njk
- remove the forgotten comma :facepalm
=> PP-10977 remove comma

src/web/modules/transactions/payment.njk
=> PP-11287 fix agreement info

src/web/modules/transactions/payment.njk
- missed % in if statement :facepalm:
=> PP-11287 fix agreement info 2

src/web/modules/transactions/payment.njk
=> PP-11287 fix agreement info 3

package-lock.json, package.json, src/web/server.js
- enable metrics scraping on `toolbox`
=> PP-11093 add metrics module

scripts/compile-assets
- Fix the flag from `--quietDeps` to `--quiet-deps`
=> PP-10784 Fix compile-assets script - update to use `--quiet-deps`

package-lock.json, package.json, src/assets/payuk-toolbox.scss, src/web/modules/common/booleanFilterSelect.njk, src/web/modules/discrepancies/report.njk, src/web/modules/gateway_accounts/create.njk, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/filter.njk, src/web/modules/layout/layout.njk, src/web/modules/payment_links/detail.njk, src/web/modules/platform/live.njk
- Changes made using the information from the V4 release notes: https://github.com/alphagov/govuk-frontend/releases/tag/v4.0.0
- Tested with Percy and required Updating styling for select boxes used for filtering.
=> PP-10784 Upgrade to Design system v4

package-lock.json, package.json
=> PP-11548: Update pay-js-metrics

src/lib/pay-request/services/connector/types.ts, src/lib/zendesk/zendesk.client.ts, src/web/modules/gateway_accounts/gatewayAccount.model.ts
For new live/test Stripe gateway accounts created, set the allow_apple_pay and allow_google_pay flags to true.
=> PP-11513 Enable wallet payments by default for Stripe accounts

src/web/modules/services/detail.njk
- updated text to clarify that users will be removed when a service is archived
--------------
--------------
=> PP-11812 Clarify that users will be removed when service is archived

src/web/modules/gateway_accounts/detail.njk
Make the Notify service ID a link to the service in Notify
=> PP-11534 Link to Notify service

src/lib/providers.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts
- Remove unused enum values
- Extract some types declared inline into interfaces
=> PP-11212 Small refactorings

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
Add row in settings table for Corporate surcharge enabled/disabled. Manage link for row replaces the green button for editing surcharge amounts.
=> PP-11212 Move corporate surcharge to manage link

src/web/modules/gateway_accounts/agent_initiated_moto.njk, src/web/modules/gateway_accounts/api_keys.njk, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/moto.njk
- Fix pluralisation of API keys
- Use italics for displaying the placeholder text in brackets when certain settings aren't configured
- Move some back links below the page heading for consistency with other pages
=> PP-11212 Minor content updates

src/lib/zendesk/zendesk.client.ts
Update the section of what's next for the Zendesk email for Worldpay go live process.
=> PP-11860 change worldpay go live message

.github/workflows/codeql.yml
Hopefully fixes the syntax error from https://github.com/alphagov/pay-toolbox/pull/1798
=> PP-12211: Move CodeQL config inside initialisation step

src/web/modules/transactions/summary_3ds.macro.njk
_Before:_
Required — version 2.2.0 (exemption not requested)
_After:_
Required (version 2.2.0) — exemption not requested
=> PP-12790 Reformat 3D Secure information on payment page

src/lib/pay-request/services/connector/client.ts, src/web/modules/transactions/confirmFixAsyncFailedStripeRefund.njk, src/web/modules/transactions/fixAsyncFailedStripeRefundErrors.njk, src/web/modules/transactions/fixAsyncFailedStripeRefundSuccess.njk, src/web/modules/transactions/fix_async_failed_stripe_refund.ts, src/web/modules/transactions/refund.njk
- Added new view for success message when async failed Stripe refund is reversed
- Added new error view to display error from connector and Stripe
=>  PP-11561 display success and errors for Async failed Stripe refund

src/web/modules/services/detail.njk
Open the email window in a new tab when clicking the 'email all admins' button
=> BAU open a new tab when clicking email all admins button

scripts/generate-dev-environment.js, src/web/modules/services/detail.njk, src/web/modules/services/services.http.ts
Don't show this button if service has a Stripe gateway account.
Have tested this locally:
=> PP-13030: Don't show Worldpay create service button

package.json
- bump cross-spawn `7.0.3` -> `^7.0.5`
=> PP-13396 bump cross-spawn 7.0.3 -> ^7.0.5

src/web/modules/gateway_accounts/csv.ts, src/web/modules/gateway_accounts/csv_with_admin_emails.ts
Add gateway account external ID to CSV downloads from the "List gateway accounts" page
=> PP-13672 Add gateway account external ID to CSV downloads

src/lib/pay-request/services/admin_users/client.ts, src/lib/pay-request/services/admin_users/types.ts, src/web/modules/users/users.http.ts, src/web/modules/users/users.show.njk, src/web/router.js
Account simplification row added to the users page:
Depends on https://github.com/alphagov/pay-adminusers/pull/2764
=> PP-13546: Enable/Disable Account simplification feature

src/lib/pay-request/services/admin_users/types.ts, src/lib/pay-request/utils/redact.ts, src/web/modules/users/users.show.njk
- Add missing fields to user class which were not showing on User details page
=> PP-13546 Add missing fields in User class

src/web/modules/users/users.http.ts, src/web/modules/users/users.show.njk, src/web/router.js
Now that the new settings have gone live, this toggle is no longer needed.
=> PP-13526: Revert account simplification toggle

browser/src/dashboard/Dashboard.tsx, src/assets/payuk-toolbox.scss, src/lib/logger.ts, src/lib/pay-request/services/admin_users/client.ts, src/lib/pay-request/services/connector/client.ts, src/lib/pay-request/services/ledger/client.ts, src/lib/validation.js, src/web/modules/agreements/detail.njk, src/web/modules/stripe/index.js, src/web/modules/transactions/csv.njk, src/web/modules/transactions/dispute.njk, src/web/modules/transactions/payment.njk, src/web/modules/transactions/refund.njk, src/web/modules/transactions/status.macro.njk, src/web/modules/transactions/transactions.http.ts, src/web/modules/users/users.http.ts, src/web/router.js
Triage of the 2025 ITHC.
Removed all comments. TBH, non of these were actual necessary todos. More like Steven's documented thought process.
=> PP-14023 triage todo comments.

package-lock.json, package.json
=> PP-14024 Update pay-js-metrics to 1.0.14

src/lib/pay-request/services/admin_users/types.ts, src/web/modules/users/users.show.njk
- show last log in date for user in user details table
=> PP-14323 Show last logged in date in user details
