alphagov/pay-toolbox

app/web/modules/stripe/legalEntity.model.js
Stripe model validation strips empty fields before sending request -
this (very manually) ensures that an empty additional_owners field is
sent to Stripe as this is an expected detail. (Pattern doesn't scale).
=> BAU: Fix stripping additional owner from model

app/web/modules/gateway_accounts/detail.njk
Previously Connector returned all values on strings on the gateway
account route - this updates the template to expect formed Bools/ Longs.
Changes accounting for https://github.com/alphagov/pay-connector/pull/1109
=> BAU: Expect data from Connector to be well formed

app/web/modules/stripe/stripe.http.js
Fixes the Stripe API version to the release closest to when this code
was written, these API calls are no longer valid and the version should
be updated when possible, this ensures the code continues to work and
requests an older API.
=> BAU: Fix Stripe API version for compatability

app/lib/pay-request/api_utils/directDebitConnector.js, app/lib/pay-request/api_utils/index.js, app/lib/pay-request/client.js, app/web/modules/gateway_accounts/create.njk, app/web/modules/gateway_accounts/createSuccess.njk, app/web/modules/gateway_accounts/detail.njk, app/web/modules/gateway_accounts/gatewayAccount.model.js, app/web/modules/gateway_accounts/gateway_accounts.http.js, app/web/modules/gateway_accounts/index.js, app/web/modules/gateway_accounts/overview.njk, app/web/modules/layout/layout.njk, app/web/modules/services/gatewayAccountRequest.model.js, app/web/modules/services/link_accounts.njk, app/web/router.js
Adds functionality to
- `Create, View, List` Direct debit Gateway accounts
- Display `gateway_account_external_id`, `toggle_3ds` only if available (Gateway Account detail page)  as these are not applicable for both Card & Direct Debit payment types
- Gateway Account's sub menu has been changed to `Card` & `Direct debit`
=> PP-4931 make direct debit account creation work

Jenkinsfile, package.json
Master builds cannot pass the Cypress tests because of an issue in the
configuration of running a seperate agent -- remove this step until this
is resolved to prevent any hanging on further PRs.
=> PP-4895: Remove failing Docker step from Jenkinsfile

Jenkinsfile
If an upstream dependency has a known fix that is not yet merged, all
PRs into this repo will be blocked by CI. By adding a parameter that is
discouraged we can continue working while waiting for the fix.
=> BAU: Make exception for known dependency fixes

.eslintrc.json, README.md, package-lock.json, package.json, src/tests/cypress/plugins/index.js
- Use typescript-eslint plugin to provide rules
- Extended recommended typescript-eslint rules along with airbnb-base
ESLint rules* Modify rules to expect an indent of 2 spaces and to allow
camelcase  for property names
- Set @typescript-eslint/no-var-requires rule to warn until we convert
modules to use Typescript module syntax
=> PP-5027 Add ESLint Typescript settings

package-lock.json, package.json, scripts/run-cypress
Cypress takes a significant amount of time to both download and unzip in
CI/ build processes - it should only be used via pre-compiled containers
during the build pipeline so having the developer set up their own
environment is the lesser of two evils.
From
To
=> BAU: Remove cypress dev dependency

src/web/modules/stripe/basic/basic.http.ts
- Provide an empty string for legal_entity.additional_owners when a Stripe account is created using the basic Stripe account creation page. This is recognised by Stripe as the organisation having nobody who owns over 25% of the business.
=> BAU - Provide additional owners for stripe account

Dockerfile
So that we can have confidence our base images aren't being changed without our
knowledge, reference them by digest instead of tag (as tags are not immutable).
Also, add a comment detailing the tag the digest corresponds to.
=> RED-45: Reference base Docker images via digest

src/web/modules/services/detail.njk
Swap the buttons around so the "Setup live Stripe account" will create the Stripe account using the details stored in the go live flow, and there is a link below to create an account the old way with all the details provided up front.
=> BAU - Make the new Stripe account creation the main button

src/web/modules/gateway_accounts/detail.njk
For CARD gateway accounts display the following details in table:
- 'Email collection mode', will be 'MANDATORY', 'OPTIONAL' or 'OFF' as
returned by adminusers
- 'Payment confirmation email', will be 'Enabled' or 'Disabled'
- 'Refund issued email', will be 'Enabled' or 'Disabled'
Should resolve issue https://github.com/alphagov/pay-toolbox/issues/45
=> BAU - Display email options for gateway account

src/lib/healthcheck.js, src/web/router.js
`/healthcheck` route, response parity with other DropWizard micro services. No further services downstream so just respond as directly healthy.
=> PP-5329 Add health check endpoint for ECS

src/config/auth.js, src/config/common.js, src/config/index.js, src/lib/logger.ts, src/lib/pay-request/client.js, src/web/server.js
* remove absolute path definitions from config (favour process instead for flexibility)
* check for non-development instead of production, allowing `test` and `staging` environments to be considered in the future
=> BAU Remove path build config requirements

package-lock.json, package.json, src/lib/auth/passport.js
Passport OAuth2 library doesn't support `https_proxy` environment
variable, override the agent until it is supported.
=> PP-5322 Use https proxy agent if httpsProxy is set

Jenkinsfile
* add pay Jenkins library
* dockerhub tag step
Temporary middle-ground between aiming to use `agent { dockerfile true }` to ensure all stages are built with the repositories configuration and making use of the `pay-jenkins-library` -- uses the manually built and tagged docker container to run each step, allowing the library steps to access the main jenkins box.
Depends on infra#2198
=> RED-80 Toolbox build/ deploy step

Dockerfile, package.json, scripts/build, scripts/compile-assets, scripts/generate-dev-environment
* Update package scripts to only run postinstall when dev dependencies
are installed
* Split build into stages
* Favour `sh` vs. `bash` - one less build step
=> PP-5060 Production dependencies only Dockerfile; include Typescript build

package.json, scripts/compile-assets, src/assets/payuk-toolbox.scss, src/lib/auth.js, src/lib/auth/github/githubStrategy.spec.js, src/lib/auth/github/strategy.js, src/web/modules/layout/layout.njk, src/web/modules/layout/user_banner.njk, src/web/router.js, src/web/server.js
User banner to give visual indication of currently authenticated user -- this is the user that will be authorising all actions/ requests and this should be made clear. 
On desktop: 
On mobile: 
Minor layout tweaks: 
* include application version in layout template 
* remove unused links 
* explicitly define and cache favicon
* remove alpha software banner
(recommend ignoring whitespace on file diff as older files cleaned up)
=> BAU User profile header

src/lib/logger.ts, src/lib/pay-request/client.js, src/web/modules/layout/layout.njk, src/web/server.js
Default all logs recorded by Toolbox service to include the authenticated user ID - anything HTTP request or internal service API that is accessed with include the session user (ref: security ticket).
* configure JSON production logging
* supplement production logs with request meta data: 
* current authenticated GitHub username (user id) 
* correlation ID to track requests through all micro services 
* toolbox ID to track requests through Toolbox service 
* format development logs to include meta details
* simplify logging in `pay-request` to leverage meta details in favour of custom strings
Micro service tracing: 
* propagate correlation ID through to other microservices, populate the `x-request-id` header if received
=> PP-5324 Application production logging

src/@types/https-proxy-agent.d.ts, src/config/server.js, src/web/modules/stripe/basic/basic.http.ts, src/web/modules/stripe/stripe.http.js, src/web/server.js
* don't (double)  set certain security headers if they are already set by proxy 
* explicitly set the https proxy agent for stripe client for production environment
=> BAU Cleanup production headers

src/web/modules/discrepancies/search_results.njk
Connector returns the raw gateway response, so we should
display it as it's very useful for debugging stuff.
=> PP-5271 Display raw gateway status

Dockerfile
Favour individual copies in favour of `COPY . .`
CI can take up to 2 minutes to run `COPY . .` command
```
15:51:01  Step 5/10 : COPY . .
15:51:57   ---> 56f51277ba45
```
https://build.ci.pymnt.uk/job/pay-toolbox/job/master/41/
```
12:09:49  Step 5/10 : COPY . .
12:10:45   ---> b293647d2ed2
```
https://build.ci.pymnt.uk/job/pay-toolbox/job/master/40/
```
17:12:42  Step 5/10 : COPY . .
17:13:38   ---> 67e58d1c8ae9
```
https://build.ci.pymnt.uk/job/pay-toolbox/job/master/38/
=> BAU Explicitly copy source folder in Docker build

.dependabot/config.yml, Dockerfile
* remove source version to meet Pay Dockerfile best practices (recently
updated by RE-D)
* add docker package manager to dependabot config
=> BAU Support docker package manager in config

package-lock.json, package.json, src/@types/https-proxy-agent.d.ts, src/web/modules/stripe/basic/basic.http.ts
Failing to build in test environment, revert to see if production environment isn't happy with this change. 
Reverts alphagov/pay-toolbox#142
=> Revert "Bump https-proxy-agent from 2.2.1 to 2.2.2"

src/lib/pay-request/api_utils/connector.js, src/web/modules/payouts/payTransaction.ts, src/web/modules/payouts/reconcile.ts
`payTransactions` to map between legacy and current payments, currently differentiated by the time we switched on the feature.
Exporting payout list as CSV to follow.
=> BAU Support legacy Stripe payments in Stripe reconciliation

src/web/modules/payouts/page.ts, src/web/modules/payouts/reconcile.ts
* given payouts may be longer than 100 transactions
* page through all results if the balance transaction has the `has_more`
flag set
=> BAU Payout reconciliation - add paging logic to retrieve any number of transactions

package-lock.json, package.json, src/web/modules/services/branding.spec.ts, src/web/modules/services/branding.ts, src/web/modules/services/services.http.ts
Both [frontend](https://github.com/alphagov/pay-frontend/blob/ce97c0c119054cecec3d2eb3a7803d142b8f05df/app/views/layout.njk#L7) and [products-ui](https://github.com/alphagov/pay-products-ui/blob/2082ea78948b0330285481f755438b9d58315d8c/app/views/includes/head.njk#L2) fall over if custom branding URLs are relative instead of absolute (don't have a proceeding `\`)
Until the whole process is improved, only write absolute URLs to admin users.
=> BAU Sanitise custom branding input

src/lib/pay-request/api_utils/adminUsers.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/services/detail.njk, src/web/modules/services/index.ts, src/web/modules/services/services.http.ts, src/web/router.js
Allow toggling of `redirect_to_service_immediately_on_terminal_state` flag on services
* avoid manually doing it in the database 
* audit-able trail of which Pay user toggled it and when
Added service action 
Expose information on service detail page
=> BAU Set failure redirect flag for services

src/web/modules/services/branding.spec.ts, src/web/modules/services/branding.ts
Setting a URL of `/` doesn't make our frontend apps happy -- allow empty strings.
=> BAU Fix empty custom branding case

src/web/modules/services/search.njk, src/web/modules/transactions/search.njk
* fix syntax error introduced on servie search page
* move description `hint` to the correct search page
=> BAU Fix services vs. transactions search page crossover

src/tests/fixtures/payment.ts, src/web/modules/transactions/@types/transactions.d.ts, src/web/modules/transactions/transactions.http.ts
* ledger `/transaction` route updated `charge_id` to `transaction_id`, this broke the API contract 
* update to expect new structure
=> BAU Fix charge_id reference -> transaction_id

src/web/modules/services/gatewayAccountRequest.model.ts
* direct debit gateway account IDs can contain strings
* don't require the link model to contain `Number`
Closes https://github.com/alphagov/pay-toolbox/issues/177
=> BAU Relax gateway account link model

src/web/modules/gateway_accounts/create.njk, src/web/modules/gateway_accounts/createSuccess.njk, src/web/modules/gateway_accounts/gatewayAccount.model.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/gateway_accounts.spec.js, src/web/modules/services/detail.njk
* fix card sandbox account bug
* conditional live statement - only make service live if the gateway account is live 
* different connectors respond with different confirmations - don't template in a service name you don't know you will get
=> BAU Fix test account link rules

src/lib/auth.js, src/lib/auth/github/githubStrategy.spec.js, src/lib/auth/github/strategy.js, src/lib/pay-request/api_utils/adminUsers.js, src/web/modules/layout/user_banner.njk, src/web/router.js
* amend github strategy
* first check if user is in administrative group 
* if not check if user has base level permissions 
* if not reject
* middleware to block requests on a router level, checks for truthful admin role to have been set on a profile at authorisation (HTTPS cookie, set only)
* block routes according to ticket reference `PP-5405`
---
* OTP codes shouldn't be served by self service user route
* until they are removed, filter them out from appearing anywhere upstream of the `GET` request
=> PP-5405 admin permission roles

src/web/modules/services/services.http.ts
Because it annoys me when I copy and paste an ID from elsewhere and it doesn’t find anything because the clipboard brought along some rogue whitespace.
=> Make service search trim whitespace from input service external ID

src/web/modules/layout/layout.njk, src/web/modules/statistics/by_service.njk, src/web/modules/statistics/statistics.http.js
* combine gateway account information with connector report route to
list gateway accounts with payment information
* include warning that this should be replaced with reporting service
routes (Ledger)
=> BAU Connector payment reporting by service

src/web/modules/services/detail.njk, src/web/modules/services/services.http.ts
* surfacing access rights for users is useful for engagement to see at a
glance
* filter this information out of the service roles object
=> BAU Show user role on service detail page

src/lib/pay-request/api_utils/ledger.js
- transaction_type='PAYMENT' is implicit (according to ledger) when `payment_states` query parameter is used.
https://github.com/alphagov/pay-ledger/blob/65453c326bca602c26c34fc6d7f0bf764b3a8315/src/main/java/uk/gov/pay/ledger/transaction/search/common/TransactionSearchParams.java#L413
=> BAU - Remove transaction_type query param

src/lib/pay-request/types/connector.ts, src/web/modules/gateway_accounts/gatewayAccount.model.ts
- Enable 3DS on live accounts for all payment providers (except Stripe)
- 3DS is enabled by default on Stripe and we don't use flag to control 3DS behaviour
=> BAU - Enable 3DS on new live accounts

src/tests/fixtures/reports.ts, src/web/modules/transactions/@types/reports.d.ts
Add types and fixtures that use these for the following report contracts
which will be produced by ledger endpoints:
- Get payments by state report. This will return the count of payments
with each state for the parameters specified.
- Get payments report. This will return some high level aggregate
statistics for payments. Initially this will be the total payment
count and the gross amount.
=> PP-5669 Add types and fixtures for ledger report contracts

src/web/modules/services/detail.njk, src/web/modules/services/overview.njk
Add "Organisation" column to the "Services" "Overview" page which contains the organisation name of the service if it is set.
Add a row to the service detail page to display the "Organisation" if the organisation name is set.
=> BAU: Display organisation name

package-lock.json, package.json, src/lib/pay-request/api_utils/ledger.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/layout/layout.njk, src/web/modules/transactions/statistics.njk, src/web/modules/transactions/transactions.http.ts, src/web/router.js
This PR adds `/transactions/statistics` route which displays the total payments, gross, success, error and in progress payments for today/this week/this month. When `transactions/statistics` is called without the `account` param it returns the information across GOV. UK Pay. When it is called with `?account=1` then it returns the information for that specific gateway account.
A 'View statistics' button is added on the gateway account page which takes us to `/transactions/statistics?account=...` route
Details:
- Adds a statistics function in ledger.js which takes in `account`, `fromDate`, `toDate` and `override` as parameters
- Adds a `/transactions/statistics` middleware which calls `transactions.statistics` in router.js
- Adds a `getPaymentsByState` function in ledger.js which calls …
=> Firebreak dashboard

src/web/modules/gateway_accounts/detail.njk
This PR surfaces to the user whether a service has Apple Pay or Google Pay enabled at /gateway_accounts/:id. This also renames 'Toggle 3DS' to '3DS enabled'
=> BAU-Display-Google-Apply-Pay-In-Services

src/lib/logger.ts
* alias log timestamps with `@timestamp` to line up with other Pay
services and the GDS Way
* camelCase -> snake_case
Interpretation depends on rules set in https://github.com/alphagov/pay-cloudwatch-logs-s3-export/pull/143
=> BAU Standard GDS Way @timestamp log attribute

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
* For Worldpay, Smartpay and EPDQ show `merchant_id`
* For Stripe show `stripe_connected_account_id`
Closes https://github.com/alphagov/pay-toolbox/issues/237
=> BAU Show account credentials for card accounts

package-lock.json, package.json, src/config/index.js, src/config/sentry.js, src/lib/logger.ts, src/lib/winstonSentryTransport.js, src/web/server.js
Add a simple Winston Transport to send 'error' level log messages to
Sentry. Since Toolbox uses Typescript we've followed a slightly
different approach than the other node apps which decorate the existing
`logger.error` function to send to Sentry. This is because the `error`
function implements the `Winston.LeveledLogMethod` interface which has
many overloaded signatures and the implemention of each signature detracts
from the simplicity of the decorating approach used elsewhere.
We decided to not use an existing third party Winston Sentry Transport as
they seem overly complex and poorly supported in comparrison to this
simpler approach.
with @stephencdaly
See local testing results sending to Sentry here:
https://pay-sentry.cloudapps.digital/sentry/toolbox/
=> PP-5765 Add Sentry

src/web/modules/gateway_accounts/detail.njk
* The gateway account details request was updated to use `v1/frontend`
in favour of `v1/api` to also fetch the PSP credentials. This was in #239
* It looks like the frontend resource uses `requires3ds` instead of
`toggle_3ds`
* Update the template to reflect that
=> BAU Update 3DS enabled key for gateway account display

src/lib/pay-request/api_utils/adminUsers.js, src/lib/pay-request/api_utils/ledger.js
The `EntityNotFound` error should be thrown for routes that are optional. 
We should have a default handler for 404 but this fixes the referenced issue.
Closes https://github.com/alphagov/pay-toolbox/issues/250
=> BAU Handle 404 on AdminUsers routes

src/web/errorHandler.ts
Only propagate error, warn on unhandled log.
=> BAU Default error handling level

.dependabot/config.yml
Not 100% if Dependabot will respect multiple entries for the same package manager, this configuration would work well for us though. 
* Patch security issues as soon as they come up (stopping Snyk/ `npm audit` from complaining) 
* Patch other updates on a weekly basis
=> BAU Dependabot live security updates

src/web/modules/transactions/transactions.http.ts, src/web/modules/users/users.http.ts
User, transaction and service searches are often copied and pasted from
tables with padded whitespace.
Trim this before searching.
=> BAU Trim top level search inputs

src/lib/pay-request/api_utils/ledger.js, src/tests/fixtures/payment.ts, src/web/modules/transactions/@types/transactions.d.ts, src/web/modules/transactions/payment.njk, src/web/modules/transactions/refund.njk, src/web/modules/transactions/transactions.http.ts
If a payment has been refunded, surface related transactions on the payment page. 
Show transaction template based on the transaction type, use newly added refund template if this is a refund.
=> BAU Show related refunds on payment page

src/web/modules/transactions/status.macro.njk
The `refundStatus` is used to show an appropriate status badge for
payments. Currently Connector marks 0p payments as "full" (amount
refunded = amount avaialble to refund) -- this doesn't mean the payment
is refunded in this case.
Follows on from https://github.com/alphagov/pay-toolbox/pull/262
=> BAU Fix 0p payments marked as "full" in refund status

src/web/server.js
* request logging middleware (morgan configuration) returns a
RequestHandler -- this wasn't being called meaning all HTTP requests
couldn't continue past this point
* return the RequestHandler so that the middleware stack continues
Will allow release of https://github.com/alphagov/pay-toolbox/pull/267
=> BAU Fix consistent logging middleware handler

src/web/modules/transactions/csv.njk, src/web/modules/transactions/transactions.http.ts
* the service from admin users is used to provide a meaningful file name 
* the ID on the top level account object refers to the service ID, not the gateway account (of which there can be multiple per service)
=> PP-5970 Fix service/ gateway account ID conflation

src/lib/pay-request/api_utils/ledger.js
- Don't specify transaction type for CSV requests
=> PP-5970 Get all transactions for CSV

package-lock.json, package.json, src/web/modules/stripe/stripe.model.js, src/web/modules/stripe/stripe.model.spec.js
Stripe expects the support phone number to be in E164 format, (e.g.
leading 0 becomes +44).
Reference this zen desk ticket for conversation with Stripe support confirming format.
https://govuk.zendesk.com/agent/tickets/3887613
=> BAU convert Stripe support phone number to E164

package.json
All pay node apps use "compile" as the build command. Adding an alias to the toolbox project saves adding complexity futher down the build pipleine and promotes reusability of shared build code.
=> Add compile command alias to build command

src/web/modules/transactions/transactions.http.ts
Updates stream comparison tool to use `v1/transaction/stream`
internally, this will be consolidated into `/v1/transaction` once this
strategy is fully implemented.
=> PP-6058 Use the proposed stream route internally

envmap.yml, manifest.yml
Adds an `env-map` buildpack allowing data provided by bound user-provided services to be mapped to application environment variables. The mapping is configured via the `env-map.yml` file. 
https://github.com/alphagov/env-map-buildpack
Using this buildpack means we do not need to alter how our app works, but rather provide a mapping from the VCAP_SERVICES var to its current name.
=> PP-6085: Add env-map Cloudfoundry buildpack

src/web/modules/transactions/payment.njk
Add a row under "Processing details" for a transaction that shows whether or not the payment is a MOTO payment.
=> PP-6074 Show whether a transaction is MOTO

package-lock.json, package.json, src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/filter.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/overview.njk
Add a filter control to the gateway accounts search to allow filtering by id and whether or not MOTO payments are enabled for the account.
The idea is that this can be extended to allow filtering the gateway account list by more properties of the gateway account.
=> PP-6072 Add filter on gateway accounts search

src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/overview.njk
We can't filter direct debit accounts in the same way, so don't show
the filter for these.
Some whitespace changes also made it in.
=> PP-6072 Don't show gateway accounts filter for dd accounts

manifest.yml
This is now defined and managed via Terraform and differs between environments.
=> PP-6127: Remove PaaS route from manifest.yml

src/web/modules/gateway_accounts/filter.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
The id field doesn't really belong here and should probably be on a separate "Find an account" page like for services/users. Remove to make it a little less confusing
=> PP-6072 Remove id field from gateway account filter

src/lib/pay-request/api_utils/ledger.js, src/web/modules/transactions/statistics.njk, src/web/modules/transactions/transactions.http.ts
Description:
- Moto payment statistics only appear for gateway accounts which have moto enabled
- Refunds and net income are also surfaced
Gateway account with moto enabled:
Gateway account with moto disabled:
=> PP-6139 - View MOTO Transactions per gateway

src/lib/pay-request/api_utils/adminUsers.js, src/web/modules/services/detail.njk, src/web/modules/services/index.ts, src/web/modules/services/services.http.ts, src/web/router.js
Small tool to allow support/ product to opt services in to experimental
features. These will most likely be gated/ prototype features in self
service that are not ready for all users but can be used by
participating services.
This is initially a simple toggle to opt in/ out but may be made more
granular in the future if more controls over prototype features are
required.
=> PP-6152 Toggle experimental features for a given service

src/web/router.js
The live payments dashboard is currently behind the secure middleware
which requires the session to have validated with GitHub OAuth before
serving the page. This requires the display machines to have access
to the other functionality provided in Toolbox. As this is served as in
internal service requiring strict internal IP access we can remove this
and allow the displays in the office to access this resource without an
OAuth session.
=> BAU Remove OAuth requirement from live dashboard route

src/web/router.js
Relates to https://github.com/alphagov/pay-toolbox/pull/304
Should have been included in
https://github.com/alphagov/pay-toolbox/pull/304, the data that actually
makes up the dashboard will also need to be available to pages that are
loaded without GitHub session.
=> BAU Dashboard data endpoints security rules

src/web/modules/gateway_accounts/detail.njk
- There was some confusion over how to toggle prepaid cards on/off, this
change brings the toggle more in line with other 'admin' operationst
toolbox users perform.
=> BAU Make Toggle Prepaid Cards A Button

package-lock.json
Address `npm audit` CI block. Webpack issues were backported for an
older dependency, reference
https://github.com/webpack/webpack/issues/10561
=> BAU bump vulnerable package lock dependencies

src/lib/pay-request/api_utils/ledger.js, src/web/modules/payouts/payTransaction.ts
As we are now expunging historic payments from Connector, Connector
should be considered a source for only live payments currently being
processed.
This has caused the payout reporting tool to `404` if it is processing
any payment or refund older than a certain age (as these payments will
have now been expunged from Connector's database).
Point the payout tool to Ledger for all transaction lookups, this data
source will guarantee the transaction (payment/ refund) is available.
=> BAU Use Ledger data source in payout reporting tool

src/lib/pay-request/api_utils/index.js, src/lib/pay-request/api_utils/products.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/payment_links/overview.njk, src/web/modules/payment_links/payment_links.http.ts, src/web/router.js
Add products helper methods for talking to the products service. Use
existing backend route for getting payment links for a gateway account.
With payment links: 
Without payment links:
=> PP-6325 List payment links for gateway account

src/lib/format.js, src/lib/pay-request/api_utils/products.js, src/web/modules/layout/layout.njk, src/web/modules/payment_links/overview.njk, src/web/modules/payment_links/payment_links.http.ts, src/web/router.js, src/web/server.js
Support showing payment links across all services, includes usage info on total number of payments created against the payment link and when it was last used. 
Depends on https://github.com/alphagov/pay-products/pull/450.
* products client helper method for payment link usage report
* grouping and ordering for last payment made against payment link and
total payments
* platfrom vs. individual gateway account links
* group payment links by gateway account
=> PP-6325 Payment links across all services

src/web/modules/payment_links/overview.njk
`account_id` -> `account` as expected by the controller filter.
=> BAU Minor fix for payment links transaction link

src/web/modules/payment_links/overview.njk, src/web/modules/payment_links/payment_links.http.ts
Use the helpful filters on the Connector gateway account route to fetch
live gateway accounts if the filter is set to true (default: true)
=> PP-6325 Payment links - filter for live gateway accounts by default

src/web/modules/payment_links/csv.ts, src/web/modules/payment_links/overview.njk, src/web/modules/payment_links/payment_links.http.ts, src/web/router.js
Allow payment links usage page to export CSV, this applies to both
individual gateway account views and the entire platform.
CSV generation should respect live account only filters and sorting on
payment date and total payments.
=> PP-6325 Payment links export CSV route

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/modules/gateway_accounts/stripe_statement_descriptor.njk, src/web/router.js
Support often have requests to update what paying users get on bank
statements for Stripe services. Allow them to do this through Toolbox.
=> PP-JFDI Allow gateway accounts to update statement descriptors

browser/src/dashboard/Chart.tsx
As our payment volume significantly increases we often go >= 1000
payments in a given hour bucket. At the moment this overflows off the
left axis of the graph.
Increase the margin to accommodate this.
**Sad with broken overflow**
**Happy with enough room**
=> BAU Fix live payments dashboard left axis overflow

src/lib/auth.js
Check if auth is disabled before looking for the user in the req as when
testing locally with auth disabled, the user does not exist
=> Allow local testing with auth disabled

src/lib/format.js, src/web/modules/transactions/list.njk, src/web/modules/transactions/payment.njk, src/web/server.js
Display timezone for date to avoid confusion with UTC vs local time zone
=> BAU - Display timezone for transaction/event dates

src/web/modules/gateway_accounts/csv.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/modules/gateway_accounts/overview.njk, src/web/router.js
Add a button to the "Gateway accounts -> Card" page to download all
gateway accounts as a CSV.
This CSV combines service and gateway account details for each gateway
account.
=> Add CSV download of gateway accounts

src/web/errorHandler.ts
We hide showing errors if a user isn't authenticated to prevent from
leaking information an unauthenticated user shouldn't see.
When authentication is disabled for local testing, we always want to be
able to see these errors.
=> Show errors when authentication is disabled

package.json
This ensures as PaaS updates available node buildpacks, the app
can continue to be deployed with minor node version updates.
i.e. 12.x.x
This matches configuration applied to other node apps.
=> Allow more flexible node version specification for PaaS apps

src/web/modules/transactions/update/update.http.ts
If no value is provided for `event_date` for a row, add in the current timestamp.
Require a value for `event_type`. We may revisit this and use a default if none is provided, we'll look at how people are using this field. Some instructions will be added to the page for what the value should look like.
Also show an error message if no CSV file is selected
=> PP-6219 Add default for event_date if not provided

src/web/modules/transactions/update/update.http.ts
Documents uploaded to the update payments bucket are encrypted using the
S3 master encryption key as they may contain sensitive data. Specify
this in put request configuration or S3 will reject the upload.
=> PP-6218 Specify server side encryption for CSV upload

src/config/aws.js, src/web/modules/transactions/update/update.http.ts
Run the ECS task to stream the CSV to the events SQS, giving the key of
the file uploaded to S3 to process.
Report back the ARN of the task so the user can check the progress in
splunk.
The task definition is provided using the
AWS_ECS_UPDATE_TRANSACTIONS_TASK_DEFINITION environment variable.
=> PP-6219 Run ECS task after file uploaded

src/web/modules/transactions/update/update.http.ts
CSV validation would fail if there were spaces before or after the
headers. Trim the headers to be more permissive.
=> PP-6219 Trim headers of uploaded CSV

src/web/modules/transactions/transactions.http.ts
Remove logic trying to determine if a successful refund has happened
before showing related transactions on a payment.
It is useful to see failed refunds against payments for support.
=> BAU Always fetch related transactions for a payments

src/web/modules/transactions/update/update.http.ts, src/web/modules/transactions/update/upload.njk
Require a "reason" to be included when updating transactions
This is to ensure we have a usable record of why payments were updated for if we need to figure out what has happened to a transaction in the future.   
Document the new required 'reason' header and restructure the "CSV headers schema" section on the page to make the required headers stand out more.
=> PP-6382 Add mandatory reason header and restructure content

src/lib/winstonSentryTransport.js
Sentry is a Typescript library that doesn't have a default export, this
means that the wildcard syntax should be used to collect all of the
modules individual exports. Without this Sentry has been failing to
intialise correctly in some cases and potentially stopping the entire
winston logging pipeline out of the app.
=> PP-6389 Fix incorrect Sentry import

src/web/modules/transactions/update/update.http.ts
We should only need to `warn` given a validation exception when
processing CSVs for updating payments.
* `logger.error` -> `logger.warn`
* use structured logging where possible to only log key info
=> PP-6387 Payment updater uses warn in favour of error logs

src/web/modules/statistics/statistics.http.js
* momentjs uses 0-indexed months and so incorrectly parses the data when received from Ledger. This fix simply subtracts 1 month so that it parses correctly.
* flush values after the header row to allow the stream to begin without
waiting on the report results
CI audit depends on https://github.com/alphagov/pay-toolbox/pull/311
=> PP-5993 Fix transaction report by month empty values

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
At the bottom of the gateway account details page, display the response for a request to get the accepted card types.
This is useful when we get notifications about blocked card types from Worldpay, as this error is the same as for a too high payment amount. We can also see if the service has since enabled the card type so we know whether or not to contact them.
=> BAU Show accepted card types for gateway accounts

src/web/modules/transactions/@types/transactions.d.ts, src/web/modules/transactions/refund.njk, src/web/modules/transactions/transactions.http.ts
The `live` column isn't provided for transactions of resource type
`refund` in Ledger. This should be passed through based on the
properties of the gateway account used to process the refund.
This updates the template to use the information attached to the parent
transaction until this is available.
=> BAU Fix refunds always showing as test data

src/web/modules/transactions/update/success.njk
Splunk payment update Dashboard allows filtering events with a
`form.job_id`. This provides aggregate information on how many of the
payment updates have succeeded or failed. This should give developers a
good idea of if the job has completed successfully without understanding
the underlying mechanics.
**Example job progress dashboard**
=> PP-6483 Payment update tool references Splunk dashboard in favour of direct search

src/lib/pay-request/api_utils/ledger.js, src/web/modules/transactions/list.njk, src/web/modules/transactions/search.njk, src/web/modules/transactions/transactions.http.ts
Allow the 'Find by transaction' search tool to try passing the field
through to `gateway_transaction_id` search filter. The same behaviour is
respected
* If nothing is found, throw search criteria not found
* If one result is returned, directly link to that transaction
* If multiple results are found, filter the main transactions view by
transaction id
=> BAU Find transaction by gateway transaction ID

.travis.yml, Dockerfile, package.json
Update to new minor Node.js version:
https://hub.docker.com/layers/node/library/node/12.18.1-alpine3.12/images/sha256-5f5cb21e96ad6ad28b6d2c1c2d5d9f3ec1a4c96ff8e130ab7d934f8e3034339c
Remove explicit NPM version in package.json and just rely on the version bundled with Node.js.
=> PP-6622 Upgrade to Node.js 12.18.1

src/web/modules/gateway_accounts/createSuccess.njk
Stripe responds with a lowercase payout statement descriptor. Display this back as upper case for copying into the email.
=> PP-6661 Make statement descriptors upper case

src/lib/pay-request/api_utils/products.js, src/lib/pay-request/api_utils/redact.js, src/lib/pay-request/api_utils/redact.spec.js, src/tests/fixtures/paymentLink.js
The products backend service only exposes an internal `v1/api` route
for payment links with all of the information used by other services.
Currently other services rely on the token used to generate payments 
through the payment link for the management of that link (deletion). 
This should be changed to use a key mapping to the token allowing 
us to remove the token from this endpoint entirely.
Until that work is prioritised, redact the tokens from the API call
before it can reach the Toolbox service/ controller code.
=> BAU Redact tokens from payment links list API

src/web/modules/statistics/statistics.http.js
- Include 'Sector' and 'Service went live date' columns in report.
- Filter out all internal and archived services.
- Filter out gateway accounts that do not have an associated service.
These can be assumed to be "archived".
=> PP-6257 Improve transactions report

src/web/modules/statistics/statistics.http.js
Currently we add a 'Starting month' to the report manually, which is the month the service started taking payments.
When generating the report for all time, include a 'Starting month' column. Don't include this when just generating a monthly report as we do not retrieve the data from ledger for this.
=> PP-6257 Add starting month for all time report

src/lib/pay-request/types/adminUsers.ts, src/web/modules/gateway_accounts/csv.ts, src/web/modules/services/index.ts, src/web/modules/services/overview.njk, src/web/modules/services/performancePlatformCsv.ts, src/web/modules/services/services.http.ts, src/web/router.js
Add a button the the "Platform services" page to download a CSV listing the active live services in the format expected by the performance platform.
=> PP-6257 Add live services CSV download

src/web/modules/gateway_accounts/createSuccess.njk
Currently, we only show the GO_LIVE_URL to replace in the macro for
newly created live Stripe accounts, along with the statement descriptors
Show the GO_LIVE_URL for all gateway accounts, as we will add this to
the macro.
=> BAU Show live account URL for non Stripe accounts

src/web/modules/services/overview.njk, src/web/modules/services/services.http.ts
When viewing "Platform services", by default only show the services that have "Go live status" of "LIVE", and do not have the "internal" or "archived" flags set to true.
Add a link to display all services.
This should help with support when trying to track down a service you're looking for e.g. based on an organisation name as many services have several old or test variants of their service.
=> BAU Only list live services by default

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/modules/gateway_accounts/stripe_payout_descriptor.njk, src/web/router.js
Provide a similar update route for the support role to update the payout
descriptor for a given Stripe account.
Payout and payment descriptors are currently separated to allow changing only what needs
configuring (it also allows linking to separate documentation). We may
find that practically these will always be the same and the UX can be
simplified.
=> BAU Allow gateway accounts to update Stripe payout descriptor

.cfignore
- Currently toolbox does not deploy correctly on PaaS because the
Cloudfoundry Cloud Controller does not let you push read only files
=> PP-6659 Add .cfignore

src/web/modules/transactions/payment.njk
Also remove a misleading “local date & time” label on the same page.
=> BAU — Put external ID on payment page

src/web/modules/transactions/payment.njk
Reverts alphagov/pay-toolbox#479 because it doesn’t seem to work.
=> Revert "BAU — Put external ID on payment page"

src/web/modules/transactions/payment.njk
Also remove a misleading “local date & time” label on the same page.
=> BAU — Put GOV.UK Pay ID on payment page

src/web/modules/transactions/update/update.http.ts
- Update the `parseInt` check to allow 0 values.
=> PP-6497 Allow 0 values for `refund_amount_available` and `refund_amount_refunded`

src/web/modules/transactions/update/update.http.ts, src/web/modules/transactions/update/upload.njk
Defaulting to 'payment' may cause people to unknowingly update the
transaction type of refunds to 'payment' if they aren't careful.
Require `transaction_type` to be specified for all updates to mean
users have to be more deliberate about this.
=> BAU Require transaction_type for transaction updates

package-lock.json
Build on master failing with
```
10:37:00  + npm audit
10:37:01  === npm audit security report ===
10:37:01
10:37:01  # Run  npm update terser-webpack-plugin --depth 2  to resolve 1 vulnerability
10:37:01
10:37:01    High            Remote Code Execution
10:37:01
10:37:01    Package         serialize-javascript
10:37:01
10:37:01    Dependency of   webpack [dev]
10:37:01
10:37:01    Path            webpack > terser-webpack-plugin > serialize-javascript
10:37:01
10:37:01    More info       https://npmjs.com/advisories/1548
10:37:01
10:37:01
10:37:01
10:37:01  found 1 high severity vulnerability in 1189 scanned packages
10:37:01    run `npm audit fix` to fix 1 of them.
```
This commit is the result of running `npm audit fix`.
=> bau: fix broken build

manifest.yml
The node build pack was being taken from upstream because at the time
toolbox was on an later version of node which the latest node
buildpack offered by PaaS included. Now that PaaS have upgraded their
node buildpack it can satisfy the node version required. Therefore
remove it and take the buildpack offered by PaaS.
=> PP-7026 Unpin the node buildpack version

src/lib/errors.ts, src/lib/pay-request/api_utils/adminUsers.js
When reporting an entity is not found, allow an optional description to
be more specific than 'ID'. This is useful if the lookup done by some
other value.
=> BAU Allow optional description to override the not found error

src/config/server.js, src/web/server.js
Set `secureProxy` flag to require secure cookies over HTTP and behind 
forward facing Nginx proxies.
According to the documentation this is a deprecated flag however it
looks like environments are rejecting the `secure` flag even though the
proxy settings look to be correctly configured in the express app.
The issue is likely caused by a header not being correctly set by the
upstream Nginx proxy, until that has been looked into, try using this
flag.
Add an environment variable to allow different environments to reduce
session time if required.
=> PP-7267 Use `secureProxy` setting for cookies

src/web/modules/services/detail.njk
Display created date if the service has one.
Fix the format for the "Went live date" and capitalize other values for
consistency.
Add some content telling toolbox users why there aren't values for the
various reporting details (sector, went live date).
=> PP-7458 Display created date on service detail

src/web/modules/services/index.ts, src/web/modules/services/overview.njk, src/web/modules/services/performancePlatformCsv.ts, src/web/modules/services/serviceExportCsv.ts, src/web/modules/services/services.http.ts, src/web/router.js
Add a CSV export that includes details about services for all services currently displayed on the service list page.
This uses filtering on the service list page to display either only live or all services.
=> PP-7458 Add service list export

.secrets.baseline, src/web/modules/common/BooleanFilterOption.ts, src/web/modules/common/booleanFilterSelect.njk, src/web/modules/gateway_accounts/filter.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/overview.njk, src/web/modules/services/filter.njk, src/web/modules/services/overview.njk, src/web/modules/services/serviceExportCsv.ts, src/web/modules/services/services.http.ts
Add filters to the service list page to filter by "Go live status", "Internal" and "Archived". Default to displaying live, not internal, not archived services.
Add Nunjucks macro for select input that has 3 options, a true value, afalse value and an "all" value.
Improve the filters on the gateway accounts list page to use the new macro and patterns. Also make it so that the the CSV download for gateway accounts obeys the filter values.
=> PP-7458 Improve search filters

src/web/modules/statistics/comparison.njk, src/web/modules/statistics/overview.njk
Add a warning to make it clear the data on the  statistics page is
coming from Connector until we can prioritise a better tool for Ledger
stats.
=> BAU Statistics disclaimer

src/web/modules/gateway_accounts/csv.ts
This is the only instance of our code using `toggle_3ds`, update this to
match the backend Connector consistency refactor.
Depends on https://github.com/alphagov/pay-connector/pull/2774
=> PP-7596 Update `toggle_3ds` to `requires3ds`

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/router.js
Add button on the gateway account detail page to toggle whether the telephone payment notifications API is enabled for the account.
=> PP-7589 Allow toggling telephone notifications for gateway accounts

src/web/modules/discrepancies/search_results.njk
- Added external status of the payment to the disprecency result UI. For expunged charges, only external status will be available and not the connector internal status which is currently shown
=> PP-7590 Add external status to disprency result view

src/web/modules/discrepancies/discrepancies.http.js
Trim IDs that are sent to connector to remove spaces. It was failing
when providing a comma separated list which had spaces.
=> BAU Trim payments ids for discrepancy checker

Jenkinsfile
We currently run Snyk on individual PRs and prioritise security
dependabot upgrades.
`npm audit` returns a non-0 status code for minor vulnerabilities
multiple layers down dependency trees. This behaviour would be useful
for when the package-lock has changed but has negatively impacted the
master building process.
Generally when small issues arise developers skip the audit process on
master because they know they aren't important, this isn't a good
pattern to reinforce.
Remove the audit from the master build step in favour of running it
against individual PRs.
=> BAU Remove npm audit step from Jenkins master build

package-lock.json, package.json
This change upgrades nunjucks from v3.2.1 to v3.2.2 and its dependencies to resolve its security vulnerabilities.
=> BAU: Upgrade nunjucks to v3.2.2

package-lock.json, package.json, src/web/server.js
Upgrade helmet from version 3 to 4.
The main breaking change is the inclusion of CSP protection by default,
as Toolbox already specifies custom CSP headers for all requests this
should require no change to the existing policies.
Reformat disabling certain rules behind a proxy as v4 no longer allows
explicit `true` to turn middleware on/ off (now favouring requiring a
configuration to be passed in).
https://github.com/helmetjs/helmet/blob/main/CHANGELOG.md#400---2020-08-02
=> BAU Update helmet dependency (major v4)

package-lock.json, package.json, src/web/modules/users/UpdatePhoneNumberForm.ts
This change bumps [class-validator](https://github.com/typestack/class-validator) from 0.11.0 to 0.13.1.
- [Release notes](https://github.com/typestack/class-validator/releases)
- [Changelog](https://github.com/typestack/class-validator/blob/develop/CHANGELOG.md)
- [Commits](typestack/class-validator@v0.11.0...v0.13.1)
It replaces `'ZZ'` with `undefined` value in region parameter in UpdatePhoneNumberFormRequest.ts to fix the following error message `TS2345: Argument of type '"ZZ"' is not assignable to parameter of type 'CountryCode'`. Source: https://github.com/typestack/class-validator/issues/871
=> BAU: Bump class-validator from 0.11.0 to 0.13.1

package-lock.json, package.json, src/config/auth.js, src/config/aws.js, src/config/common.js, src/config/logger.js, src/config/sentry.js, src/config/server.js, src/config/services.js, src/web/modules/statistics/dateFilter.model.js, src/web/modules/stripe/address.model.js, src/web/modules/stripe/bankAccount.model.js, src/web/modules/stripe/dob.model.js, src/web/modules/stripe/legalEntity.model.js, src/web/modules/stripe/stripe.model.js, src/web/modules/transactions/legacy/transactionSearch.model.js
Update 3 major versions to [Joi](https://github.com/sideway/joi) 17. 
A breaking change in schema definition and the top level Joi `validate` method requires updating usage of the library.
https://joi.dev/resources/changelog/
=> BAU Update Joi validation library to 17

.secrets.baseline, package-lock.json, package.json, src/lib/pay-request/api_utils/adminUsers.js, src/lib/pay-request/types/adminUsers.ts, src/web/modules/gateway_accounts/createSuccess.njk, src/web/modules/gateway_accounts/gatewayAccount.model.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/services/detail.njk, src/web/modules/stripe/basic/confirm-create-test-account.njk, src/web/modules/stripe/basic/test-account.http.ts, src/web/modules/stripe/index.js, src/web/modules/stripe/model/account.model.js, src/web/modules/stripe/model/person.model.js, src/web/router.js
- Added functionality to create test Stripe connect account and a test gateway account (Stripe). Test account can only be created when service requests (from selfservice) for Stripe test account.
- Uses Stripe latest library to create test account as per Stripe docs https://stripe.com/docs/connect/testing
- Stripe library (v7.15.0) still exists to create live accounts. Moving to latest library could mean we need to request connect account capabilities explicitly and the `legacy_payments` capability required for live accounts is no longer supported by Stripe.
=> PP-7738 Create Stripe test account

src/web/modules/stripe/basic/confirm-create-test-account.njk, src/web/modules/stripe/basic/test-account.http.ts
- Fix name of Stripe test API key as provisioned in environments.
- Minor changes based on story review comments https://github.com/alphagov/pay-toolbox/pull/884
=> PP-7738 Fix Stripe test API key name

src/assets/payuk-toolbox.scss, src/web/modules/transactions/payment.njk
Long payer names without space breaks have difficulty overlapping, allow
spaces to break to the next line but limit unbroken text with `...`.
**Behaviour following change**
=> PP-7784 Fix transaction page payer text overlap

src/lib/pay-request/api_utils/connector.js, src/web/modules/stripe/basic/test-account.http.ts
with @SandorArpa
-  When creating a Stripe test account, we want all the Stripe setup values
to be true.  So that in Self service there are no banner messages shown
telling the user add extra Stripe info - e.g. bank account, VAT number.
=> PP-7739 Creating Stripe Test Account - set Stripe setup values to true.

src/lib/pay-request/api_utils/adminUsers.js, src/lib/pay-request/types/adminUsers.ts, src/web/modules/gateway_accounts/csv.ts, src/web/modules/gateway_accounts/csv_with_admin_emails.ts, src/web/modules/services/detail.njk, src/web/modules/services/index.ts, src/web/modules/services/services.http.ts, src/web/router.js
Add a button for toggling the `agent_initiated_moto_enabled` flag on a service.
=> PP-7710 Add ‘Toggle agent-initiated MOTO payments enabled flag’ button

.secrets.baseline, src/lib/pay-request/api_utils/products.js, src/lib/pay-request/api_utils/publicAuth.js, src/lib/pay-request/api_utils/redact.js, src/lib/pay-request/api_utils/redact.spec.js, src/lib/pay-request/types/products.ts, src/web/modules/gateway_accounts/CreateAgentInitiatedMotoProductFormRequest.ts, src/web/modules/gateway_accounts/agent_initiated_moto.njk, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/router.js
Add a page in toolbox to allow us to create an `AGENT_INITIATED_MOTO` product for a gateway account (along with an API key for it).
=> PP-7711 Add ability to create AGENT_INITIATED_MOTO products

src/web/modules/transactions/update/update.http.ts, src/web/modules/transactions/update/upload.njk
Add validation to the transaction update tool to ensure that the value given for the optional `reproject_domain_object` column in the CSV is one of "true" or "false".
Provide instructions for use of the `reproject_domain_object` header in the update transactions CSV.
=> PP-7906 Validate and document reproject_domain_object column header

src/web/modules/services/detail.njk
"Toggle" isn't very helpful as it doesn't tell you whether the feature is currently enabled. Reword so the button says "enable" when a flag is false and "disable" when it is true. This mirrors buttons for flags on the gateway account page.
=> BAU Reword toggle service settings buttons

src/web/modules/stripe/basic/test-account.http.ts
- Remove validation for Stripe test account requests so we can create test accounts without the user requesting the same from selfservice.
=> BAU - Remove Stripe test account validation

src/web/modules/stripe/basic/confirm-create-test-account.njk, src/web/modules/stripe/basic/test-account.http.ts
Add a non-blocking warning as a reminder to developers/ admins when
adding a test account to a service.
This isn't intended to block the process but should hopefully catch
mistakes if the wrong service is selected.
=> BAU Warn user if service hasn't requested stripe test account

src/web/modules/layout/layout.njk, src/web/modules/services/getFilteredServices.ts, src/web/modules/services/services.http.ts, src/web/modules/statistics/performance.http.ts, src/web/modules/statistics/performancePage.njk, src/web/router.js
Add a route to generate the HTML for the static performance page.
This generates the main body of the page and fills in the statistics about the services and organisations using Pay. This is returned as raw HTML to be copied into the product page file and released.
It leaves the payment statistics blank as these currently need to be queried directly from the database due to performance concerns.
Link to this page from a page containing instructions for updating the product page.
=> PP-7931 Generate performance page HTML

src/lib/pay-request/api_utils/adminUsers.js, src/web/modules/services/detail.njk, src/web/modules/services/index.ts, src/web/modules/services/services.http.ts, src/web/router.js
Currently to archive a service we have to make a SQL update via the production database.
To make developer's lives less stressful, we've added a simple toggle button in Toolbox to do this, in a similar way to the other toggle methods on the service page.
- Adds Archived status in the top info box
- Adds short description of the impact of archiving (i.e. only for reporting purposes)
- Calls Adminusers to make the change to the service.
=> ZD-4531285 Add archive service button

src/web/modules/statistics/statistics.http.js
Description:
- Ledger no longer processes timezones for gateway monthly performance report - see https://github.com/alphagov/pay-ledger/pull/1201
=> PP-8026 - Send Ledger no timezone information for request for gateway monthly performance report

browser/src/dashboard/ledgerResource.ts, src/web/modules/platform/dashboard.http.ts
Description:
- Ledger` /performance-report` endpoint can only parse LocalDate so the corresponding call will only send LocalDate - see https://github.com/alphagov/pay-ledger/pull/1207
=> PP-8026 - Refactor performance report to send dates without timezone

src/web/modules/statistics/performance.http.ts, src/web/modules/statistics/performancePage.njk
Description:
- The performance data for number of transactions and total volume in the .json file can be queried from Ledger via the /transaction-summary endpoint
- This PR updates the code so that it is added into the .json file removing the need to query Ledger using the SQL on the page
=> PP-8030 - Modify performance json to use Ledger numbers

src/web/modules/statistics/performance.http.ts
Description:
- Toolbox now uses the /performance-report Ledger endpoint for performance data
- Performance data json file now displays results in millions
JSON now displays as following:
`{
"dateUpdated": "4 May 2021",
"numberOfPayments": "1.2 million",
"totalPaymentAmount": "123.5 million",
"numberOfServices": 0,
"numberOfOrganisations": 0,
"serviceCountBySector": {},
"serviceCountByOrganisation": {}
}`
=> PP-8026 - Performance data to use Ledger performance endpoint

src/web/modules/statistics/performance.http.ts
- Changes to query ledger for successful payment volumes for performance data
- Extended method to convert units to billion which is fast approaching for total amount and total_amount is returned as pence so converted to pounds
=> PP-8026 Filter successful payments for performance data

src/web/modules/gateway_accounts/agent_initiated_moto.njk
Update the hint text for the form fields used to create an agent-initiated MOTO product (telephone payment link) to match those used in the team manual, which have the benefit of being reworded by a professional writer.
=> BAU — Update agent-initiated MOTO form field hints

browser/src/dashboard/EventCard.tsx, browser/src/dashboard/ledgerResource.ts, src/web/modules/platform/dashboard.http.ts, src/web/modules/transactions/types/ledger.ts
Decorate service names that are passed to the browser with an
`is_recent` property if they have gone live within the last 30 days.
Callout recent services with a tag associated with each event.
=> BAU Callout new services on the payments dashboard

.github/dependabot.yml, package-lock.json, package.json, src/lib/gatewayAccounts.ts, src/web/modules/transactions/update/update.http.ts, src/web/server.js
Update dependabot config
* restrict to production dependencies, development dependencies should
be bumped by developers where functionality or performance is needed.
Dev dependencies can also be bumped for security patches
* limit to 5 open PRs to avoid build up all at once
* remove dev dependency specific rules
---
Update from aws-sdk v2 to v3. Import only the clients required (S3 and
ECS).
Update AWS code syntax with default promise behaviour.
=> BAU Sense check dependabot cadence

src/lib/pay-request/api_utils/connector.js, src/lib/pay-request/types/adminUsers.ts, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts, src/web/modules/gateway_accounts/switch_psp/switch_psp.njk, src/web/modules/stripe/basic/account.ts, src/web/modules/stripe/basic/basic.http.ts, src/web/router.js, src/web/server.js
Add page to configure card accounts for switching payment service provider.
- add helper methods for new connector endpoints
- separate out provisioning stripe production account so it can be used both by go live and switch psp routes
- add page controller and template for switching psp
- expose gov uk frontend JavaScripts to the browser to make use of conditional radios on the page
**Switch PSP page**
**Stripe requires basic information not provided during initial go live**
**Warn about accounts that are already switching**
=> PP-8192 Support accounts switching PSP

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts
Add backend validation to top new credentials being added when the
account is already set up for switching. There is already a warning
but this should prevent any possibility of multiple non-terminal
(pre-ACTIVE) credentials existing on any given account.
Show the status of an accounts switching on the account detail page.
=> PP-8192 Restrict account provider switching if already enabled

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/router.js
- For the Gateway Detail page
- Add `toggle` to send payer email to Worldpay
- Update router with new route to toggle sending payer email to Worldpay
- Update the gateway account module with new methods.
- Update connector util with new method to call new connector method to update this toggle.
=> PP-8255 Toggle - For sending payer email to Worldpay for fraud protection

src/web/server.js
Following recommendation that a timeout of 15-30 minutes should be used
for data on this application, reduce the duration property for session
expiration.
=> PP-8280 Reduce authorised client session duration to 30 minutes

src/lib/auth.js, src/lib/auth.spec.js, src/web/router.js
Store the URL being accessed when fetching tokens from GitHub to refresh
sessions. Redirect to this if authorisation is successful.
Add coverage for the session being cleared up to avoid session pollution.
=> BAU Remember and redirect to URL after authorisation

src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts, src/web/modules/gateway_accounts/switch_psp/switch_psp.njk, src/web/modules/stripe/basic/test-account.http.ts
Setup stripe test account if gateway acount is test, set all account
stripe flags to true as the admin tool currently has no way of
configuring stripe test accounts (access to test key etc.)
For production accounts, favour `req.ip` instead of manually parsing socket connection and
headers. `req.ip` will take the left most address if behind a proxy and
receiving multiple x-forwarded-for addresses.
=> PP-8218 Allow switch to setup stripe test accounts

src/web/modules/gateway_accounts/gateway_accounts.http.ts
The gateway account credential data model changed when credentials were
decoupled from accounts themselves. This relies on the top level
credential which is no longer available.
Update to use `stripe-account` endpoint to get the correct credential,
this should eventually be updated to parse all available
credentials/ integrations when that pattern is formalised.
=> BAU Fix stripe account id not available for stripe descriptors

src/lib/stripe/stripe.client.js, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/payouts/page.ts, src/web/modules/payouts/reconcile.ts, src/web/modules/stripe/basic/account.ts, src/web/modules/stripe/basic/test-account.http.ts
- Added stripe client which returns stripe legacy module (supporting stripe api version 2018-09-24). This can be extended to abstract stripe sdk methods from toolbox services or web modules.
- Also uses Stripe constructor to set httpAgent instead of using deprecated `setHttpAgent`
=> PP-8555 Add Stripe client

package-lock.json, package.json
Reverts alphagov/pay-toolbox#1215
Observed something in the stack unexpectedly throwing
```
error: {
code: ERR_INVALID_PROTOCOL
}
```
Suspect it's related to additional protocol parsing added to the sentry client with partial commit `88b96f6c401`  but further investigation would be needed.
=> Revert "Bump @sentry/node from 6.12.0 to 6.13.1"

src/web/modules/gateway_accounts/createSuccess.njk, src/web/modules/stripe/basic/test-account.http.ts
The Zendesk macro for when a Stripe test account is created does not ask
for the dashboard URL, so remove this from the success page as it is
misleading.
=> BAU unused remove macro placeholder data

package-lock.json
Updates ansi-regex, validator and passport-oauth2 via `npm audit fix`.
- [ansi-regex changelog](https://github.com/chalk/ansi-regex/releases/tag/v5.0.1) (fixes [CVE-2021-3807](https://nvd.nist.gov/vuln/detail/CVE-2021-3807))
- [validator changelog](https://github.com/validatorjs/validator.js/blob/master/CHANGELOG.md) (fixes [CVE-2021-3765](https://nvd.nist.gov/vuln/detail/CVE-2021-3765))
- [passport-oauth2 changelog](https://github.com/jaredhanson/passport-oauth2/blob/master/CHANGELOG.md) (fixes [CVE-2021-41580](https://nvd.nist.gov/vuln/detail/CVE-2021-41580))
=> PP-8876: Address Toolbox vulnerabilities

src/web/modules/stripe/basic/test-account.http.ts
For test accounts we don't need to provide director information for them
to be enabled. Mark the `director` setup task in connector as done so
that users will never be shown the banner on the dashboard to add these
details.
=> PP-8834 Mark director task as done for Stripe test accounts

src/lib/pay-request/types/adminUsers.ts, src/web/modules/stripe/basic/account.ts, src/web/modules/stripe/basic/basic.http.ts
- Creates Stripe live accounts with new capabilities (`card_payments` & `transfers`)
- Updated to latest Stripe version (`2020-08-27`) to create accounts
- Stripe client initialisation be moved in separate .client js when legacy version has been removed fully
=> PP-8865 Create stripe accounts with new capabilities

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
This stopped displaying when we implemented PSP switching. Display the
connected Stripe account ID or the PSP merchant ID for the ACTIVE
credential.
=> BAU Show PSP account ID for active credential

src/web/modules/stripe/basic/account.ts
A recent change introduced a mistake where the Stripe test API key is
being used to create accounts that should be in Stripe production.
=> BAU Use Stripe production key for creating production accounts

src/web/modules/stripe/basic/account.ts
This is a required field before accounts can begin taking payments, so set when creating an account.
=> PP-8861 Send product description when creating Stripe accounts

src/web/modules/gateway_accounts/gateway_accounts.http.ts
This was broken when we updated to the latest Stripe API version.
=> PP-8972 Fix not showing statement descriptors

src/web/modules/stripe/success.njk
- With stripe version update, response payload from stripe has changed and business name is no longer available as top level field `business_name` and instead moved to `company.name`.
- We can just use merchant name available on service instead.
=> Fix: Stripe success template: use organisation name available on service

src/web/modules/gateway_accounts/detail.njk
Make the stripe account id displayed in the gateway account a link to the account in the stripe dashboard
=> BAU: Add link to stripe account in Gateway account page

src/lib/pay-request/api_utils/ledger.js, src/web/modules/platform/dashboard.http.ts
A new endpoint was added to get performance statistics using the ledger
`transaction_summary` table.
We had reverted to using the legacy endpoint for the performance page
JSON download, which queries the `transaction` table resulting in poor
performance and burst balance drops. This was done by mistake as the
same ledger client method is used by the live payments dashboard.
Create a separate client method that will query the legacy endpoint just
for use by the live payments dashboard.
with @SandorArpa
=> BAU Use new ledger performance report endpoint

src/lib/pay-request/api_utils/adminUsers.js
To update the email the 'op' is 'replace' and 'path' is 'email'. See https://github.com/alphagov/pay-adminusers/pull/1229.
=> PP-9203: Set correct path to update email

src/lib/pay-request/types/connector.ts, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
Now that stripe accounts are created with the credential having a state
of CREATED rather than ACTIVE, display the connect account id or PSP
merchant ID for the  only credential if there is only 1 credential, else
for the active credential
=> BAU Show Stripe account ID for only or active credential

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
Account detail page
- Show notification banner when it is a LIVE account without PSP credentials
- For all accounts
- Show new field - Credentials state
- Shows `ACTIVE` if there is an active credential.
- Otherwise, shows the current state of the first credential.
=> BAU - Live Account with no Active credentials - show warning and extra info

src/lib/auth/github/permissions.js
See https://developer.github.com/changes/2020-01-21-moving-the-team-api-endpoints/ for details of the API change and https://github.blog/changelog/2022-02-22-sunset-notice-deprecated-teams-api-endpoints/ for why it’s suddenly become pressing right now.
=> BAU — Update the GitHub teams API URL to a non-deprecated one

src/lib/pay-request/api_utils/connector.js, src/lib/pay-request/types/connector.ts, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
For Stripe gateway account, display a list of the Stripe setup steps the
service is yet to complete. This will help us determine what we've
submitted to Stripe on their behalf as sometimes it can be unclear from
the Stripe dashbaord.
Separate out the table of gateway account details into smaller tables to
make it easier to visually parse:
- Gateway account details
- PSP details
- Self-serve settings
- Toolbox configurable settings
=> BAU Display outstanding Stripe setup tasks

src/web/modules/gateway_accounts/gateway_accounts.http.ts
This task is only completed during switching PSP so most services don't
have this completed. Don't list it in the outstanding Stripe task list
for gateway accounts.
=> BAU Don't show "Organisation details" stripe task

.github/workflows/post-merge.yml, .github/workflows/run-tests.yml
This PR follows the pattern of separating out post-merge into a separate workflow for future use in release tagging in GHA.
There are no pact-tests to port into GHA for toolbox
=> PP-9239: Separate post-merge into file

src/web/modules/statistics/statistics.http.js
- toolbox was upgraded to Node 16. res.flush() is no longer supported. we need to use res.flushHeaders().
=> BAU fix statistics csv download

src/lib/pay-request/api_utils/ledger.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/transactions/list.njk, src/web/modules/transactions/transactions.http.ts
Add a "View refunds" link on the gateway account details page to list
all refunds for a gateway filtered by state.
This uses the same page as the payments list, and just changes the
ledger transaction search query based on a query parameter.
Rename the "View transactions" link to be "View payments".
=> BAU Add list refunds page

src/web/modules/transactions/list.njk
Add in the transaction type query parameter to the URLs for the
pagination links, so that the correct transaction type is displayed when
they are used
=> BAU Fix refunds page pagination

.gitignore, package-lock.json, src/lib/pay-request/types/connector.ts, src/tests/fixtures/payment.ts, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/services/detail.njk, src/web/modules/services/services.http.ts, src/web/modules/transactions/payment.njk, src/web/modules/transactions/transactions.http.ts, src/web/modules/transactions/types/ledger.ts, src/web/server.js
Toolbox now provides links to corresponding entities in the stripe dashboard for payments and gateway accounts. These links are context aware and will route to the correct Stripe environment.
Additionally:
- Toolbox now provides a [CORP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)), this fixes a bug preventing GitHub avatars loading
- Toolbox now shows the payment provider and type when listing gateway accounts associated with a service (previously just id was shown)
=> PP-9442 link payments and gateway accounts to stripe dashboard where appropriate

src/lib/pay-request/api_utils/adminUsers.js, src/web/modules/users/deleteUserFromService.njk, src/web/modules/users/users.http.ts, src/web/router.js
As this is destructive functionality we're adding the `auth.administrative` middleware to the `/users/:userId/service/:serviceId/delete` endpoint.
=> PP-8827: Implement remove user from service functionality

src/lib/pay-request/api_utils/connector.js, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/router.js
Add a fine button to enable or disable recurring payments for a gateway account. Button comes in both red (to enable) and green (to disable) with other colours available for a custom development fee.
Tested this locally and it flipped that boolean in the database real good.
=> PP-9553 Add button to enable recurring payments on gateway account

src/web/modules/stripe/basic/test-account.http.ts
When we create a Stripe test account, we set all the setup flags to completed so that we don't ask services to provide any additional information, as all dummy information required to verify a test account is provided upfront.
We recently added the government_entity_document flag, but weren't setting this when creating test accounts.
=> BAU Set government_entity_document flag when Stripe test account created

src/web/modules/gateway_accounts/email_branding.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
Allow setting the "email_reply_to_id" property on the "notify_settings" object on the gateway account. This allows us to specify different reply-to email addresses for services for the same organisation that require the same email branding whilst using the same Notify service.
=> PP-9632 Allow configuruing reply-to email per account

src/web/modules/transactions/dispute.njk
Add template to render dispute transactions, including the basic information.
Template is copied from the refund template and slightly altered.
The template name rendered for a transaction will match the transaction type, so no code change for the controller is required to render this.
.
=> PP-9626 Render dispute transactions

src/web/modules/transactions/payment.njk
In the "Related transactions" table on the payment page, add a column for the transaction type. This will currently be either "Refund" or "Dispute"
=> PP-9626 Display related transaction type

src/lib/errors.ts, src/lib/pay-request/config.ts, src/lib/pay-request/typed_clients/base.ts, src/lib/pay-request/typed_clients/client.ts, src/lib/pay-request/typed_clients/services/admin_users/client.ts, src/lib/pay-request/typed_clients/services/connector/client.ts, src/lib/pay-request/typed_clients/services/ledger/client.ts, src/lib/pay-request/typed_clients/services/products/client.ts, src/lib/pay-request/typed_clients/services/public_auth/client.ts, src/web/errorHandler.ts, src/web/server.js
When the server starts, configure the typed clients to:
- pull the correlation id out of the logging context stored using
cls-hooked and use this to set the `x-request-id` header on requests.
- log the details of the request on success/failure.
Ensure that the Axios interceptors are only added once, when the `config`
method of `src/lib/pay-request/typed_clients/client.ts` is called, which
is done in the server startup. To do this, remove configuring Axios from
the constructor for the Clients.
Handle errors thrown by Axios when making requests in the way toolbox
currently handles these errors from the old client code.
The typed clients were previously wrapping errors using the `HttpError`
per request. Instead, wrap the AxoisError into the RESTClientError type
already used by toolbox, which …
=> PP-9814 Configure typed clients

src/web/modules/gateway_accounts/stripe_payout_descriptor.njk, src/web/modules/gateway_accounts/stripe_statement_descriptor.njk, src/web/modules/gateway_accounts/switch_psp/switch_psp.njk, src/web/modules/stripe/basic/basic.njk
Several forms in toolbox ask for a bank statement descriptor for Stripe services, either to appear on the paying user’s statement, or the service’s statement when they receive a payout, or both.
Consistently specify the requirements for the length and allowed characters for statement descriptors.
Source: https://stripe.com/docs/statement-descriptors#requirements
=> BAU — Put requirements for statement descriptors in more places

src/web/modules/transactions/update/update.http.ts, src/web/modules/transactions/update/upload.njk
Edit validation for the transaction update CSV upload to allow for `transaction_type` of dispute, and require the `parent_transaction_id` to be present for a dispute.
Add `live` and service_id` to the optional headers in the instructions for creating the CSV
=> PP-9873 Allow updating dispute transactions

src/web/modules/transactions/dispute.njk
Only display a fee row on the dispute details page when a fee exits. Add a row for the net amount.
Without fee:
With fee:
=> BAU Dispute dispute fee and net amount correctly

package-lock.json, package.json
This fixes https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24434.
=> PP-9900: Bump multer to 1.4.5

src/web/modules/transactions/update/update.http.ts, src/web/modules/transactions/update/upload.njk
- We currently require CSVs to update transactions uploaded to toolbox to have a “reason” column to explain why the transaction was updated for auditing purposes. Disputes are now using a field also called `reason` to store the reason why a payment was disputed. Change the requirement for the CSV upload to have a column named `update_reason` rather than `reason`.
=> PP-9925 rename reason to updated_reason for csv update uploads

src/lib/pay-request/typed_clients/base.ts, src/lib/pay-request/typed_clients/services/connector/client.ts, src/web/modules/events/events.http.js
Use typed clients in events.http.js
Send Content-Type header with value 'application/json' for all requests.
=> PP-9814 Use typed clients for administrative tasks

src/web/modules/transactions/payment.njk
On the page for a payment, include the time next to each refund in the related transactions list because it is common for several refund attempts to be made in quick succession.
This will change the displayed timestamp from something like “Mon Oct 03 2022” to something like “3 Oct 2022, 16:45:12 UTC”.
=> BAU — Include time with refunds list on payment page

browser/src/dashboard/EventCard.tsx, src/lib/pay-request/typed_clients/services/ledger/client.ts, src/web/modules/platform/dashboard.http.ts
Re-applies this with fix for the issue that was causing 500 responses previously:
The issue was that the client method to call the event ticker ledger API endpoint was trying to to manipulate the payment_provider on returned events without checking whether it is present on the event first.
=> PP-9814 Use typed clients for dashboard

src/web/modules/stripe/basic/account.ts
- Since the new Stripe contract, we have been creating Stripe accounts as government_entity. But verification checks seem different as Stripe has moved the existing connect accounts to `government_agency` to stop triggering additional checks/deadlines on their side.
- Although we got mixed info from Stripe and no confirmation yet for the type of account, we think we should just change it to `government_agency` as it is what Stripe has done for accounts.
=> BAU: Create Stripe connect account as government_agency

package-lock.json, package.json, src/web/modules/transactions/list.njk, src/web/modules/transactions/search.njk, src/web/modules/transactions/transactions.http.ts
- Often on support we get queries from paying users about their transactions. So it would be useful to search transactions by email to offer advice to users or find services to redirect users to.
- Extended functionality to search transactions by email. If no transactions are found continue the search by reference or transaction ID.
- Preview
=> BAU: Search transactions by email

browser/src/dashboard/Dashboard.tsx, browser/src/dashboard/EventListPanel.tsx, browser/src/dashboard/ledgerResource.ts, src/assets/payuk-toolbox.scss, src/web/modules/transactions/types/ledger.ts
The live payments dashboard currently doesn't handle failures, usually this will result in it "hanging" or no longer showing current events as the main event loop has stopped running.
Common failure scenarios are:
- Intermittent WiFi
- Connecting to another known network not on an allowed domain list
- The tab being unfocussed for a long period of time causing the main event loop to not be run
Introduce a connection state, when there are any failures when communicating with the network, reset the connection and have the dashboard reconnect when possible. Backoff on connection attempts until a specified maximum number of attempts.
This also allows us to appropriately reconnect when crossing a day boundary.
The connection state is reflected visually to help anyone running the dashboard to …
=> BAU Manage dashboard connection state (reconnect on network failures)

src/lib/pay-request/services/products/client.ts
This should make the agent-initiated MOTO configuration page stop telling lies about what’s already set up.
=> BAU — Make listing products by type actually filter by type

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
- 'integration_version_3ds' is displayed for all accounts (including stripe) in Toolbox but it is only required for Worldpay accounts.
- For Stripe accounts, `integration_version_3ds` is never used anywhere (by Connector or any other processes)
- So re-purposed 3DS enabled & integration version 3ds fields on the UI to '3DS Flex' and only displaying for Worldpay accounts.
=> PP-10249 Rename '3DS enabled' to '3DS Flex enabled'

src/lib/pay-request/services/connector/client.ts
The payment parity checker (between Connector and Ledger) is returning a 500 if the payment is missing from Connector (has been expunged).
Add the standard handler on the client so that the correct error (404) is propegated.
=> PP-10399 Handle not found errors for connector charges

src/web/modules/gateway_accounts/gateway_accounts.http.ts
Include some key service information when services go live. This can then optionally be used to provide reports on services that are currently going live.
=> PP-10434 Add logging for services going live

src/web/modules/gateway_accounts/email_branding.njk
Update the hint text to make it clearer that when we ask for a Notify reply-to email address ID, we want an ID of an existing reply-to address configured in the Notify account and not an email address.
Also update some other labels to match the admin tool.
=> BAU — Notify reply-to email address ID takes an ID, not an email

src/web/modules/gateway_accounts/gateway_accounts.http.ts
Add simple validation that an email isn't entered for the "Reply-to email address ID" field on the page to update email branding. We've seen it can be quite easy to mis-read this field and enter an email address.
=> PP-10277 Add validation that email isn't entered

src/web/modules/stripe/basic/basic.http.ts, src/web/modules/stripe/index.js, src/web/router.js
Endpoint `/stripe/balance` is no longer needed as this has been superseded by https://github.com/alphagov/pay-connector/pull/4232
This reverts commit 3c4d46a001b72b88a5dae29ec1e16e80aa61ced1.
=> Revert "PP-10542: Endpoint to log stripe balance (#1550)"

src/lib/auth/github/permissions.spec.js, src/lib/auth/github/permissions.ts, src/lib/auth/github/strategy.js, src/lib/auth/github/strategy.spec.js, src/lib/auth/types.ts
We were attempting to return false if the user was not a member of any group, and 0 if the user was a member of the VIEW_ONLY group. We were then checking the truthy value of the result, which evaluates as false for both results.
Make the interface of the permission check function clearer to return a result for whether the user is permitted, as well as their permission level.
Also add some code comments explaining the different permission levels.
=> PP-9958 Fix permission level check for VIEW_ONLY users

src/lib/auth.spec.js, src/lib/auth/types.ts
Modify the enum so that VIEW_ONLY has a value of 1 rather than 0.
This means checks like the following won't evaluate to false because the permission level has a value of 0:
```
if (req.user.permissionLevel && req.user.permissionLevel >= permissionLevel) {
```
=> PP-9958 Fix permission checks for VIEW_ONLY users

src/web/modules/agreements/agreements.http.ts, src/web/modules/agreements/detail.njk
The Pay data model has not yet been updated to ensure one service only has one test and one live integration per service. When this work is done we can get integrations/ accounts from connector by using the service identifier.
For now support getting multiple accounts back and present these to the user.
=> PP-10635 Fix: allow multiple accounts for agreement

src/lib/pay-request/services/connector/client.ts, src/lib/pay-request/services/connector/types.ts, src/lib/pay-request/services/ledger/types.ts, src/web/modules/agreements/agreements.http.ts, src/web/modules/agreements/detail.njk
Fixes 0e94e99dcf559699453d4a0daeb4b603b4a69d85
As we don't return the account ID on the agreement - only the service_id whether it is live or test, we need to get the gateway account using the service ID. We were incorrectly providing the query parameter for searching by service id.
=> PP-10635 Fix get account for agreement

src/web/modules/ledger_payouts/list.njk, src/web/modules/transactions/status.macro.njk
- Make the status tag colours match up to what they were before:
- 'in-transit' - grey tag
- 'failed' - orange tag
=> PP-10634 Update status tag colours

src/web/modules/gateway_accounts/gatewayAccount.model.ts, src/web/modules/gateway_accounts/gateway_accounts.spec.js
- set the flag `requires_3ds` to true when creating a Worldpay test account
with @alan-gds
=> PP-10731 set 3ds required to true for Worldpay test accounts

package-lock.json, package.json, src/lib/zendesk/zendesk.client.ts, src/web/modules/gateway_accounts/confirm.njk, src/web/modules/gateway_accounts/createSuccess.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
Update go live request ticket with current go live macro when making a service live. Unfortunately solving the ticket using the zendesk client is troublesome at the moment as the custom fields "[Pay] Type of user" and "[Pay] Type of user other (enter detail)" need to be populated first. This is certainly possible but is something we can make happen later.
[Video that shows successful updating of a ticket from toolbox](https://gds.slack.com/archives/CADKX7Q93/p1680519574656169).
Screenshot of "Gateway account created" page in my local toolbox:
=> PP-10864: Update go live request ticket (for Worldpay only)

src/lib/pay-request/services/ledger/client.ts, src/lib/pay-request/services/ledger/types.ts, src/web/modules/agreements/agreements.http.ts, src/web/modules/agreements/detail.njk
The agreement detail page now displays a list of the agreement's events, fetched from Ledger, similarly to the transaction detail page.
=> PP-10701: List agreement events on details page

src/lib/zendesk/zendesk.client.ts
For some reason, the payout statement descriptor wasn't capitalized at https://govuk.zendesk.com/agent/tickets/5305853. Capitalize all descriptors to make them consistent with what we've manually entered for all time.
=> PP-10864: Capitalize descriptors

src/lib/pay-request/services/webhooks/client.ts, src/lib/pay-request/services/webhooks/types.ts, src/web/modules/webhooks/detail.njk, src/web/modules/webhooks/overview.njk, src/web/modules/webhooks/status.macro.njk, src/web/modules/webhooks/webhooks.http.ts, src/web/router.js
* Endpoint for webhook details page is `/webhooks/{id}`
* Accessible via links in the webhooks overview page
* The macro which renders webhook statuses as badges contained the wrong values and mapped to the wrong colours, so this has been changed to bring it in line with the mappings used in the admin tool.  (https://github.com/alphagov/pay-selfservice/blob/master/app/views/webhooks/_webhook_status.njk)
=> PP-10537: Add webhooks detail page

package-lock.json, package.json
[qs](https://www.npmjs.com/package/qs) is a dependency of `request`, [which is no longer maintained](https://www.npmjs.com/package/request). So here we've added an override to get the latest compatible version of `qs`.
=> PP-10951: Update qs to v6.11.1

package-lock.json, package.json, src/lib/zendesk/zendesk.client.ts
- Removing `node-zendesk` NPM and replacing with `axios`.
- The repo is already using `axios` v0.26. Did try updating to a newer version but caused a lot of Typescript errors.
- This will have to be done at another time.
- In order to use the Zendesk API key, we need to do the following:
- Use basic auth as follows: - Username - use the API username with /token at the end. - Password - set as API key
- axios will automatically detect if the http_proxy ENV variable is set and use that to proxy requests.
- The http_proxy ENV is set on the AWS environments.
- When running it locally, no proxy is used.
- Cannot use the `url-join` NPM module in this repo due to a TypeScript issue with the NPM module in this repo.
-  Therefore, the ZENDESK_URL env var - must not contain a / at the end.
=> PP-10894 Remove the node-zendesk npm package and use axios

src/lib/pay-request/services/webhooks/client.ts, src/web/modules/webhooks/messages/detail.njk, src/web/modules/webhooks/messages/overview.njk, src/web/modules/webhooks/webhooks.http.ts, src/web/router.js
Adds a new page to show the details of a webhook message, this will be linked from all source in a follow up commit. Including:
- helper client wrapper to access message detail backend endpoint
- controller, template and router to link them together
=> PP-10537 Add new webhook message detail page

src/lib/pay-request/services/webhooks/types.ts, src/web/modules/transactions/payment.njk, src/web/modules/transactions/transactions.http.ts, src/web/modules/webhooks/messages/detail.njk
Make it easy to check if a service has webhooks subscribed to certain payments by putting associated webhook messages on the payments page.
Do this by:
- checking if there are any webhooks associated with the service
- checking for messages assoicated with those webhooks and this resource (this is because messages are a sub-resource of webhooks)
Use the precedent set by other components on the page for a centred no data found message.
=> PP-10895 Add associated webhook messages to the payments page

src/web/modules/webhooks/detail.njk, src/web/modules/webhooks/messages/detail.njk, src/web/modules/webhooks/messages/overview.njk, src/web/modules/webhooks/overview.njk
A few tweaks to make navigating around webhooks in Toolbox better:
- include links to associated services/ accounts from pages to support digging down into detail and back up
- add subheadings to separate content and actions
- order subscriptions alphabetically to stop them moving in-place
- address visual issue when no`last_delivery_status` existing when a message hasn't been attempted yet
=> PP-10537 Quality of life improvements for webhooks

src/web/modules/gateway_accounts/gateway_accounts.http.ts
After updating the service on the backend, we're logging values from a service object fetched before the update.
Change this to log the value that we just updated the service with.
This will allow reports/ log searches to appropriately filter out services that have been made live for internal purposes.
=> BAU Fix incorrect service live flag on go lives

src/lib/pay-request/shared.ts, src/web/modules/agreements/list.njk, src/web/modules/agreements/states.ts, src/web/modules/agreements/status.macro.njk
We don’t have any process/code that sets the payment_instrument/agreement status to expired. Also don’t have any plans to set payment instruments to expired status.
- replace expired with inactive status
=> PP-10977 remove expired status from agreements

src/lib/pay-request/services/webhooks/types.ts, src/web/modules/transactions/transactions.http.ts, src/web/modules/webhooks/webhooks.http.ts
- We now require the gateway account ID when calling webhook functions.
- This PR is to update calls to webhooks.
- The backend changes will be done once this is merged in.
=> PP-11020 Update API calls to Webhooks to include `gateway account id`

src/lib/pay-request/services/connector/client.ts, src/lib/pay-request/services/connector/types.ts, src/web/modules/agreements/agreements.http.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts, src/web/modules/ledger_payouts/payout.http.ts, src/web/modules/payment_links/payment_links.http.ts, src/web/modules/services/services.http.ts, src/web/modules/transactions/transactions.http.ts, src/web/modules/webhooks/webhooks.http.ts
There are 2 endpoints for getting an account by the internal ID: `/v1/api/accounts/{accountId}` and `/v1/frontend/accounts/{accountId}`
These both now return exactly the same response. We intend to remove the `/frontend/` variant, so use the `/api/` variant in all places.
=> PP-11244 Use /api/ variant of GET account endpoint

package-lock.json, package.json
Reverts alphagov/pay-toolbox#1723
This wasn't happy on deployment to test-12 - I think the new version doesn't work well with the OAuth
=> Revert "Bump https-proxy-agent from 5.0.1 to 7.0.1"

.github/dependabot.yml
See RFC: https://github.com/alphagov/pay-architecture/discussions/97
We can simplify the existing configuration that ignores dev dependencies and AWS etc, by setting Dependabot to only generate security update PRs for the `npm` package ecosystem.
=> PP-11138 Dependabot security updates only

src/tests/fixtures/payment.ts, src/web/modules/transactions/payment.njk, src/web/modules/transactions/types/ledger.ts
The payment page in Toolbox includes information on the payment, how it was processed and its event timeline. Add rows to include information about recurring payments in the “Processing details” section of the page.
- Recurring: True if authorisation mode == agreement else False
- Agreement: (agreement_id) (links to agreement detail page) if transaction has agreement_id
=> PP-11287 add auth mode and agreement id to transaction detail page

src/web/modules/gateway_accounts/detail.njk
Worldpay credentials in the response from connector now include a "one_off_customer_initiated" field that is always populated with the one off credentials if they are set. The "merchant_id" and "username" at the root of the credentials object will no longer be present for Worldpay accounts that set/update credentials in the future.
Use the `one_off_customer_initated.merchant_code` field to display the Worldpay merchant code.
=> PP-11152 Read merchant code from new credentials structure

src/lib/pay-request/services/admin_users/types.ts
We no longer have username as such stored in adminusers and we are not going to include it in any responses that contain user info.
- remove username from User.class
=> PP-11327 remove username from User class

src/lib/pay-request/services/admin_users/client.ts
Adminusers is searching by email. The method in Toolbox is called findByEmail. It makes sense to rename the payload's field to email instead of username.
=> PP-11327 switch using email to find a user

src/lib/pay-request/services/admin_users/client.ts
Adminusers is searching by email. The method in Toolbox is called findByEmail. It makes sense to rename the payload's field to email instead of username.
=> PP-11327 switch using email to find a user part 2

scripts/compile-assets
- Add the `--quietDeps` flag to the SASS compilation step to hide warnings from design system SASS files.  Design system will be updating these in the future but have to leave them in for now to ensure backward compatibility.
- Warnings will still be shown from any of our SASS files
=> PP-10784 Update compile assets script

src/web/modules/services/detail.njk, src/web/modules/services/services.http.ts
- When a service is archived, we currently remove users from the service and redact gateway account credentials
- We can also revoke API keys as users will not have access to service.
=> PP-11812 Revoke API keys when a service is archived

src/lib/pay-request/services/connector/types.ts, src/web/modules/gateway_accounts/email_branding.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
For configuring email custom branding for a gateway account, add a required field to set the Notify Service ID.
No changes in connector are required for this, as connector accepts and stores any JSON for the `notify_settings` property for a gateway account.
Add simple validation for the form to configure email branding using the Joi library.
=> PP-11634 Collect Notify service ID

src/web/modules/gateway_accounts/detail.njk
If email, branding is configured, show the Notify settings.
Also fix formatting for gateway account details template. Remove conditional for direct debit as direct debit has been retired and change h1 headers to h2.
There are some indentation changes, so hiding whitespace from the diff might make it easier to see what's changed.
=> PP-11634 Display email branding configuration

package-lock.json, package.json, src/lib/pay-request/services/connector/types.ts, src/web/modules/gateway_accounts/check_notify_service_id.http.ts, src/web/modules/gateway_accounts/csv_data.ts, src/web/router.js
For PP-11634 some of the Notify service IDs were backfilled incorrectly due to a copy-paste error.
Add a temporary utility route that will check the stored service ID by making a request to the Notify API to send an email using the API key set for the custom branding for a gateway account. Although use the magic notify email address that won't actually send an email. Check the service ID returned in the `template_uri` field in the response matches the service ID we had stored in connector.
This route will be removed after it has served its purpose.
=> PP-11634- Add temporary Notify service ID checker utility

src/web/modules/services/index.ts, src/web/modules/services/services.http.ts
- Try/catch in controller methods rather then using the wrapAsyncErrorHandlers method in the exports. This should make code navigation easier.
- Use the ES6 `export function` delcaration. This should mean fewer clicks in an IDE when navigating to/from usages.
Hiding whitespace changes will make this a lot easier to review.
=> PP-11212 Refactor services controller

src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts, src/web/modules/services/detail.njk, src/web/modules/stripe/account.ts, src/web/modules/stripe/accountDetails.model.ts, src/web/modules/stripe/confirm-create-test-account.njk, src/web/modules/stripe/index.js, src/web/modules/stripe/live-account.njk, src/web/modules/stripe/stripe-account.http.ts, src/web/modules/stripe/test-account.http.ts, src/web/router.js
We had the routes `/stripe/basic/` and files in a folder named "basic" for creating Stripe accounts.
This is because previously there was a "not basic" way of creating accounts where we needed to configure more account details. Since the old routes and files no longer exist, "basic" no longer makes any sense. So rename the files and routes accordingly.
=> PP-11212 Rename Stripe files and routes

src/web/modules/layout/layout.njk
- Re-order the sections in the side navigation to be more in order of usage.
- Rename some links to make it clearer what they're for.
- Rename "Platform services" etc. to "List services" etc.
=> PP-11212 Re-order and rename links in side nav

src/web/modules/gateway_accounts/confirm.njk, src/web/modules/gateway_accounts/create.njk, src/web/modules/gateway_accounts/gatewayAccount.model.ts, src/web/modules/gateway_accounts/gateway_accounts.spec.js, src/web/modules/stripe/test-account.http.ts
This was added when we supported Direct Debit, which has now been retired. If we add another new payment method we might configure accounts in a different way - so remove radio buttons on the create gateway account page which only had one option - "Card".
=> PP-11212 Remove payment method selection for creating gateway account

src/lib/liveStatus.ts, src/lib/pay-request/services/admin_users/types.ts, src/lib/providers.ts, src/web/modules/gateway_accounts/create.njk, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gatewayAccount.model.ts, src/web/modules/gateway_accounts/gateway_accounts.exceptions.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/gateway_accounts.spec.js, src/web/modules/services/AddTestAccountForm.ts, src/web/modules/services/detail.njk, src/web/modules/services/go_live.njk, src/web/modules/services/index.ts, src/web/modules/services/services.http.ts, src/web/modules/services/test_account.njk, src/web/modules/stripe/confirm-create-test-account.njk, src/web/modules/stripe/live-account.njk, src/web/modules/stripe/stripe-account.http.ts, src/web/modules/stripe/success.njk, src/web/modules/stripe/test-account.http.ts, src/web/router.js
Replace the 3 buttons on the services page to create live and test gateway accounts for Stripe/Non-Stripe with just 2 buttons:
- Go live
- Add test account
> <img width="699" alt="image" src="https://github.com/alphagov/pay-toolbox/assets/5648592/73ff8640-3172-499b-a175-9e8a0e3c45b4">
When "Go live" is clicked, determine the PSP from the go-live stage for the service. 
> <img width="757" alt="image (1)" src="https://github.com/alphagov/pay-toolbox/assets/5648592/89a9334f-80c3-4c22-9542-1668e5cb1e56">
If the service hasn't completed a go-live request, show an error.
> <img width="745" alt="Screenshot 2024-01-10 at 14 19 08" src="https://github.com/alphagov/pay-toolbox/assets/5648592/305f67a2-5a33-4876-a87a-207f73dc7fcc">
When "Add a test account" is clicked, show a new page with radio …
=> PP-11212 Improve go-live and test account journeys

src/web/modules/gateway_accounts/detail.njk
- We're aiming to get to a place where we can remove all the red buttons at the bottom of the gateway account details page. All these settings will be accessed by clicking a "Manage" link in the settings summary tables.
- As a first step, restructure the settings tables into more appropriate categories.
- Use the new summary card design system component.
- For now, the only "Manage" link exists for the "Email branding" as this already just links out to another settings page so was easy to move.
- Made a few small cosmetic changes
=> PP-11212 Restructure gateway account details page

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/switch_psp/switch_psp.njk
Replace most of the remaining buttons on the gateway account details page.
- All the green buttons that were links to related pages have been replaced with a list of hyperlinks.
- The "Manage API Keys" button has been replaced by displaying the number of API keys in the "Account details" summary list and adding a "Manage" link.
- The "Switch PSP" button has been replaced with a "Manage" link in the PSP configuration summary list.
- The Stripe statement descriptor buttons have been replaced by fetching and displaying the statement descriptors in the "Stripe configuration" summary table and adding "Manage" links.
The changes are highlighted in red on the screenshot below:
=> PP-11212 Replace most of buttons on gateway account page

src/web/modules/gateway_accounts/detail.njk
Fix displaying whether corporate surcharge is enabled or not on the gateway account details page. Looks like there was copy-paste error and I didn't test this properly.
=> Fix corporate surcharge flag

src/lib/zendesk/zendesk.client.ts, src/web/modules/gateway_accounts/gatewayAccount.model.ts, src/web/modules/gateway_accounts/gateway_accounts.spec.js
- Enable Apple Pay by default when creating Wordlpay accounts (both test and live).
- Update Zendesk micro to reflect the change
=> PP-11860 default Apple Pay enabled for Worldpay

src/web/modules/gateway_accounts/detail.njk, src/web/modules/transactions/payment.njk
Context: CodeQL warned us that 'External links without noopener/noreferrer are a potential security risk.'
Add noopener / noreferrer attributes to the two external links.
=> PP-12083 Add noopener and noreferrer to external links

package-lock.json, package.json, src/web/modules/layout/layout.njk
- Bump govuk-frontend so we can use the new crown.
- Update the header to use the Nunjuks macro from govuk-frontend
- Enable the option to show the new crown
=> PP-12247 Bump govuk-frontend and update header

.github/workflows/codeql.yml
Changes the CodeQL config file to:
- enable scans on push to `master` branch (this was overlooked previously)
- only scan files in the `/src/**` folder. Note that this is separate to the trigger for the workflow ("only run the workflow if a file in `/src/**` is changed" versus "when the workflow is run,  scan stuff in `/src/**`")
If this works OK I'll adjust the config in the other app repositories.
=> PP-12211 CodeQL: restrict files to scan and enable on push

src/web/modules/agreements/list.njk, src/web/modules/gateway_accounts/detail.njk, src/web/modules/ledger_payouts/list.njk, src/web/modules/transactions/list.njk, src/web/modules/transactions/payment.njk, src/web/modules/webhooks/messages/overview.njk
- Do not show •••• when we have no digits at all from the card number to show but do have some card details available (this can happen if a service prefills the cardholder name but the user has not yet entered their card number)
- Consistently using blue tags (one was accidentally light blue, which is not even a colour in GOV.UK Frontend 4)
- Consistently use entities for ampersands in link URLs
=> PP-12509 More at-a-glance payment info: follow-up fixes

src/web/modules/agreements/list.njk, src/web/modules/transactions/list.njk
If the value of a Nunjucks variable is assigned with a set expression and that variable is later displayed in the template, autoescaping will convert any `&` characters to `&amp;` — so the variable value should just use `&` characters.
This regression was introduced by commit e96dc1c16b79e0baa3215cfd121d8994b15f2da6.
=> PP-12549 Fix bug where & in some links encoded as &amp;amp;

src/web/modules/payment_links/payment_links.http.ts, src/web/modules/services/getFilteredServices.ts
According to the ITHC, we should use primitive types unless there's a good reason not to. Fair enough!
=> PP-12696: Use primitive types

src/web/modules/transactions/features.macro.njk, src/web/modules/transactions/payment.njk, src/web/modules/transactions/summary_3ds.macro.njk
If a payment required 3D Secure, add a ‘3DS’ tag to its page.
Add a new 3D Secure row to the processing details table, stating whether the payment required 3D Secure, the 3D Secure version (if known) and any information about whether an exemption was requested and whether or not it was honoured (if available).
=> PP-12790 Add 3D Secure information to payment page

src/web/modules/transactions/payment.njk, src/web/modules/transactions/transactions.http.ts
Add a fairly crude calculation of how long the paying user spent on the payment pages entering their card details etc.
Example: 1 hour, 5 minutes and 17 seconds
=> PP-12790 Add user journey duration to payment page

src/web/modules/transactions/transactions.http.ts
Add how long the paying user spent on the payment pages for some failed payments (such as when the authorisation was rejected, the user cancelled the payment or there was an error during authorisation). In most of these cases the user will be shown an error page and the duration will not include how long they spent reading this page but it still gives an idea.
=> PP-12790 User journey duration for some failed payments

src/lib/pay-request/services/connector/client.ts, src/lib/pay-request/services/connector/types.ts, src/web/modules/transactions/confirmFixAsyncFailedStripeRefund.njk, src/web/modules/transactions/fix_async_failed_stripe_refund.ts, src/web/modules/transactions/refund.njk, src/web/router.js
- Added routes for dealing with failed Stripe refunds
- Added refund button for failed Stripe refunds
- Added post requests to post to connector endpoint to reverse failed Stripe refund
- Added new confirmation page for failed Stripe refunds
Note: the `github_user_id` comes from the Github's API (https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#get-a-user). There was no easy way to test this locally but looking through Splunk I am confident the `req.user && req.user.username` is the correct Github username.
=> create button to fix failed Stripe refund

src/web/modules/layout/layout.njk, src/web/modules/users/search.njk
This has caught me out several times over the years. The [Find A User](https://toolbox.payments.service.gov.uk/users/search) search page is looking for service users only, in the Adminusers database. This PR renames the page and the sidebar to make that clear.
I've also linked to the [Find A Transaction](https://toolbox.payments.service.gov.uk/transactions/search) search, to help developers who need to look up paying users.
=> PP-12433: Clarify that the Find A User search is for service users

src/web/modules/users/search.njk
I mistakenly put the paragraph outside the `{% main %}` block 🤦‍♀️ 
That will serve me right for moving things around at the last minute to be 'neater' and not doing a subsequent check locally.
=> PP-12433: Move user search guidance text inside main block

src/web/modules/common/messagesSummary.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/services/detail.njk, src/web/modules/services/services.http.ts, src/web/modules/services/services.update_organisation.njk
- prompt user to add org name when creating a gateway account for a service (if none set)
- add new messagesSummary macro
- show system messages on update_organisation view
- adopt new card summary component on service detail view
- fix small layout bug on service detail view affecting render of page footer
=> PP-13069 prompt for org name instead of throwing an unhandled error

src/lib/pay-request/services/ledger/client.ts
- when looking up charges with gateway transaction id, ensure that any unusual characters are encoded to prevent bad request errors being returned
=> PP-13003 encode uri path components when querying ledger endpoints

README.md, src/config/server.js, src/index.js
Bind to 127.0.0.1 by default instead of 0.0.0.0 and allow override with BIND_HOST env var.
You can see this works, on master:
* On master run `npm run dev`
* Then netstat:
```
$ netstat -anl | grep 3000
tcp46      0      0  *.3000                                        *.*                                           LISTEN.
```
* Switch to this branch, then `npm run dev`
* Then netstat:
```
$ netstat -anl | grep 3000
tcp4       0      0  127.0.0.1.3000                                *.*                                           LISTEN
```
* Now `BIND_HOST=0.0.0.0 npm run dev`
* A final netstat to prove the override works
```
$ netstat -anl | grep 3000
tcp4       0      0  *.3000                                        *.*                                           LISTEN
```
Example of the …
=> PP-13145: Accept BIND_HOST env var and default to localhost

src/web/modules/transactions/discrepancies/validateLedger.http.ts, src/web/modules/transactions/discrepancies/validateLedger.njk
This change removes the obviously unnecessary differences, that decision is based on a successful transaction on my local environment.  It allows 10 milliseconds time difference between Connector and Ledger's timings.
This was initially committed as work in progress but I've started to see it as a step in the right direction and worth merging while we continue to look at the rest of the page.
(Paired with @james-peacock-gds)
=> Inital simplification of parity summary page.

src/lib/pay-request/services/connector/client.ts, src/lib/pay-request/utils/error.ts, src/web/modules/transactions/discrepancies/validateLedger.http.ts, src/web/modules/transactions/discrepancies/validateLedger.njk
Context: The parity check in toolbox compares responses from connector and ledger in relation to a given transaction. It should only check the fields that are common to both responses, highlighting any missing or different fields. If connector returns 404 (charge not found), a message should be displayed rather than an error page.
- Omit some fields which are specific to connector or ledger (i.e. those which are not common to both).
- Handle a 404 from connector by way of a message on the parity check page rather than presenting an error page.
- Improve layout so that differences in values, and missing fields, are shown under separate sub-headings
=> PP-12854 Parity check - omit unnecessary fields and handle connector 404

src/web/modules/transactions/discrepancies/validateLedger.http.ts, src/web/modules/transactions/discrepancies/validateLedger.njk
Context: Parity check is failing for at least one transaction in production.
- Add logging in the event that the parity check fails to provide further info for investigation
- Also, add `auth_3ds_data` to the list of excluded fields because this field is only ever present in the connector response.
=> PP-12854 Add logging for failing parity check

src/web/modules/transactions/discrepancies/validateLedger.http.ts
Context: the parity check is failing for at least one payment in connector. This has been traced to a bug in the latest improvements to the parity check. If the responses from connector and ledger are identical, the diff returns `undefined`, which is expected behaviour according to the [npm docs](https://www.npmjs.com/package/deep-diff#diff) but we failed to code for this. This wasn't spotted sooner because in the vast majority of cases there is a small difference in the `created_date` (which creates a valid diff and small differences in created_date are subsequently filtered out).
- if the responses from connector and ledger are identical, don't attempt to filter the `undefined` result from `diff`, just display the page showing that there are no differences.
=> PP-12854 Allow for identical responses in parity check

src/lib/pay-request/services/ledger/types.ts, src/web/modules/transactions/discrepancies/validateLedger.http.ts
Context: When Stripe notifies Pay of a dispute, the payment's `refund_status` is updated in ledger. Connector does not have knowledge of disputes, so parity checks will show a discrepancy for `refund_status` for disputed payments. A [previous PR](https://github.com/alphagov/pay-connector/pull/5547) ensured that this would not prevent payments from being expunged from connector. Therefore showing this discrepancy in the toolbox parity check is not helpful.
- Disregard discrepancies in refund_status in parity checks for disputed payments.
This has been manually tested locally using a payment where the `refund_status` has been updated to `unavailable` in ledger and `disputed=true` has been added to the ledger `transaction_details` field.
Before this change, this payment shows the discrepancy …
=> PP-13106 disregard refund summary in parity check for disputes

src/web/modules/transactions/fix_async_failed_stripe_refund.ts
-The refundId and the chargeId were the wrongway round so when the endpoint was called wrong ID was passed
- This pr puts them the right way
=>  PP-13247-fix-order-of-endpoint

src/web/modules/services/detail.njk
At the moment the only reason is because Worldpay test services cannot be made live.
=> PP-13030: Indicate why there's no go live button

package-lock.json, package.json
Update `pay-js-commons` to `v6.0.15`
- This is a change of two major versions, but should be safe.
- There are only minimal changes to the code between these versions (diff can be seen [here](https://github.com/alphagov/pay-js-commons/compare/v4.0.2...v6.0.15))
- The changes almost entirely pertain to the new `axios` client, which is not used as toolbox uses `axios` directly
- The only uses of `pay-js-commons` in toolbox are `constants.webhooks.humanReadableSubscriptions` and logging formats from `logging`, which do not appear to be impacted by the changes in this upgrade
=> PP-13280 Update pay-js-commons to 6.0.15

.github/workflows/codeql.yml
For Toolbox, the typescript files we want to scan are in a different folder (src).
This PR accompanies the change in https://github.com/alphagov/pay-ci/pull/1322 to adjust the workflow to handle Typescript scans as well as Node.
=> PP-12244: Use Typescript option for CodeQL scans

scripts/run-dev, src/lib/pay-request/services/public_auth/client.ts, src/lib/pay-request/services/public_auth/types.ts, src/web/modules/gateway_accounts/api_keys.njk, src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/index.ts, src/web/modules/gateway_accounts/revoked_api_keys.njk, src/web/modules/services/services.http.ts, src/web/router.js
- Add page to show revoked API keys with links between active and revoked API key pages
- Update text on "Delete API key" button to "Revoke API key"
- Update heading on "Manage API keys" page to "Manage active API keys for Gateway account [ID]"
Links to API key pages on gateway account:
New revoked API keys page:
Updated active API keys page
=> PP-11009 Add page for revoked API keys

src/web/modules/transactions/discrepancies/validateLedger.http.ts
The `settled_date` field does not appear in the Connector response, so should be excluded from the Parity Check validator page (see below for a screengrab of how this currently looks):
=> BAU: Exclude Ledger settled_date field from Parity Checker

src/web/modules/gateway_accounts/detail.njk, src/web/modules/gateway_accounts/gateway_accounts.http.ts
- use "revoked" in place of "deleted" in success banner
- update "1 API Key" to "1 active API Key"/"1 revoked API Key" on gateway account page
=> PP-11009 Update content on API key pages

browser/src/dashboard/Dashboard.tsx, browser/src/dashboard/EventCard.tsx, browser/src/dashboard/EventListPanel.tsx, browser/src/dashboard/Spring.tsx, browser/src/dashboard/events.ts, browser/src/dashboard/format.ts, src/assets/payuk-toolbox.scss
Builds on @sfount's branch with changes to the live payments dashboard:
- Adds a toggle option to show/hide unsuccessful payment events
- Smoother transition of the event ticker
- Removes the 'pence' on the `Value of complete payments` and `Value of all payments today` stats, to reduce the amount of fast-moving numbers on screen
- Adds the preset `config.slow` to the `ValueSpring` animated component in an effort to slow things down even more
=> PP-13510: Slow down the dashboard

src/web/modules/stripe/account.ts
- Stripe doesn't allow upper case (HTTPS://)in URLs. So change the scheme & host to lowercase before sending it to Stripe
=> ZD6038173 Change `scheme and host` to lowercase when sending to Stripe

src/lib/pay-request/services/connector/types.ts, src/web/modules/payment_links/detail/detail.http.ts, src/web/modules/payment_links/list/list_all.http.ts, src/web/modules/payment_links/search/search.http.ts
PR #1878 introduced a few issues with the payment link pages, with the `detail` and `search` controllers specifying the wrong template path, and the live accounts not being filtered correctly
this fixes these issues
=> PP-13672 Fix some issues with payment links pages

src/web/modules/payment_links/account/list_account.http.ts, src/web/modules/payment_links/account/list_account_csv.http.ts
#1878 introduced a small issue with the ordering of payment links on the account payment links pages not being ordered according to the selected option
This fixes that issue
=> PP-13672 Fix account payment links page to properly order links

src/lib/pay-request/services/connector/types.ts, src/web/modules/gateway_accounts/csv_data.ts, src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts, src/web/modules/payment_links/list/list_all_csv.http.ts, src/web/modules/services/services.http.ts, src/web/modules/transactions/transactions.http.ts, src/web/modules/webhooks/webhooks.http.ts
The type of `gateway_account_id` on the `GatewayAccount` type was listed as `string`, however in many cases it is returned by Connector as a number. Since types are not enforced at runtime, the type of `gateway_account_id` would be `number` in cases where it is returned as a number by Connector. This causes some issues where it is expected to be a string, but these are not picked up at compile time.
Changing the type on the object to `number` requires that it be explicitly converted to a string in cases where it is being used as a string.
=> PP-13672 Make type of gateway_account_id on GatewayAccount a number

src/web/modules/agreements/status.macro.njk
- Update code for displaying tags on agreements pages - so that it is in sentence case and complies with V5 govuk-frontend guidelines.
=> PP-12022 V5 - fix agreement tags

src/assets/payuk-toolbox.scss, src/web/modules/layout/layout.njk
- Make the contrast ratio of the colours accessible.
- Update the styling so that it goet all the way across the screen.
=> PP-12022 Update `test data` banner

src/lib/pay-request/services/connector/client.ts, src/web/modules/services/detail.njk, src/web/modules/services/services.http.ts
###  What
- adds a tag to show which accounts are shown to services following degatewayaccountification
- this should aid support work by making it easy to determine which test account a service is using
- also adds an error to the service page if the test account returned by connector is not associated with the service in adminusers
screenshots:
=> PP-13826 highlight accounts that will be shown to degatewayed services

src/web/modules/services/services.http.ts
- Add the gateway account ID to the error message added in #1890
=> PP-13826 Include gateway account ID in misconfigured service error message

src/web/modules/services/services.http.ts
This fixes a bug introduced in #1890 where if Connector returned no test account for a service, toolbox would only show an error
This instead shows a warning that no test account was found
New view:
old view:
=> PP-13826 Fix error message shown when no test account is found

src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts
- when enabling psp switch on a worldpay account, ensure that stripe onboarding is reset
=> PP-12428 reset stripe onboarding when enabling psp switch for account

src/web/modules/transactions/dispute.njk, src/web/modules/users/users.show.njk
- add tags to show user's role on each service on User page
=> ZD-6110472 Show service roles on User page

src/web/modules/transactions/refund.njk
=> BAU — Remove rogue ‘g’ from refund page

src/lib/pay-request/shared.ts, src/web/modules/transactions/transactions.http.ts
[PP-14146](https://payments-platform.atlassian.net/browse/PP-14146)
Previously, transactions which were disputed were incorrectly displaying the refund template.
This change causes the dispute template to be displayed which is the intended behaviour. 
[PP-14146]: https://payments-platform.atlassian.net/browse/PP-14146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PP-14146 toolbox uses refund template to display dispute

src/lib/pay-request/services/admin_users/client.ts, src/web/modules/agreements/agreements.http.ts, src/web/modules/common/ifEntityNotFound.ts, src/web/modules/gateway_accounts/gateway_accounts.http.ts, src/web/modules/gateway_accounts/moto.http.ts, src/web/modules/gateway_accounts/switch_psp/switch_psp.http.ts, src/web/modules/layout/layout.njk, src/web/modules/ledger_payouts/payout.http.ts, src/web/modules/payment_links/account/list_account.http.ts, src/web/modules/payment_links/account/list_account_csv.http.ts, src/web/modules/transactions/transactions.http.ts
- allow viewing transactions which are orphaned in Ledger, i.e. the `gateway_account_id` on the transaction corresponds to a Gateway account which does not exist in Connector
- show error messages when viewing orphaned transactions
Screenshots:
=> PP-12481 Show orphaned transactions

package-lock.json, package.json, src/web/modules/layout/layout.njk
Updating `govuk-frontend` module to version 5.10.2 and adding global nunjucks to enable the branding. See new branding below:
=> PP-13895 update frontend and header

src/web/modules/layout/layout.njk, src/web/modules/platform/live.njk, src/web/server.js
Enabling the new favicon in the header:
=> PP-13942 enabling new favicon in header

src/lib/pay-request/services/connector/client.ts, src/web/modules/transactions/payment.njk, src/web/modules/transactions/refund.njk, src/web/modules/transactions/transactions.http.ts
- add a tag to show if a transaction has been expunged or not for charges & refunds (disputes are not stored in Connector)
Screenshots:
=> PP-14377 Show whether a transaction is expunged for charges & refunds
